### ISSUE TITLE
Error compiling taskintf

### ISSUE THREAD

**Issue by TurBoss** [LinuxCNC/linuxcnc#100]
Hi

Configure output: http://dpaste.com/2HAGKHS
Error: http://dpaste.com/0EB8BRS

I'm having this error when compiling master branch 3e93bfa14ecf1653b8c38ef6d1c1f51c330148ca  on ubuntu 16.04

i'm building a simulator with --with-realtime=uspace

Thx

**Comment by SebKuzminsky** [comment]
Looks like a conflict in the definition of isnan() between the standard C++ header file "cmath" and boost.

Try the attached patch, which tells it to prefer the cmath implementation over the boost one.

[isnan-patch.txt](https://github.com/LinuxCNC/linuxcnc/files/342738/isnan-patch.txt)

**Comment by jepler** [comment]
Looks like we regressed, this was fixed once before at commit 9d6a5bc0.  If the  patch isn't adequate, please re-open this issue with the next compile error if it looks like it's also about `isnan`, or open a new issue if it looks like something else.

**Comment by TurBoss** [comment]
it has passed the but still compiling fine

will tell if finish

**Comment by TurBoss** [comment]
now I'm getting this

http://dpaste.com/0GED3Z0

**Comment by TurBoss** [comment]
sry can't reopen so I'm goin to create a new one
