### ISSUE TITLE
isnan error while compiling

### ISSUE THREAD

**Issue by TurBoss** [LinuxCNC/linuxcnc#101]
continue part of #100 

Error: http://dpaste.com/0GED3Z0

lineardeltakins.cc fails to build on ubuntu 16.04

**Comment by jepler** [comment]
I created a 16.04 virtual machine, and after the above commit I got a full build.  Tests failed until I added the patch in #102, which is also in our master branch now.  I didn't try any interactive/graphical features before I blitzed the VM and called it a day.
