### ISSUE TITLE
debian configure script needs python option

### ISSUE THREAD

**Issue by rene-dev** [LinuxCNC/linuxcnc#1135]
debian configure script needs python option needs python version, as some os versions can build python2 and 3 packages.
this also makes installing dependencies easier.
https://github.com/LinuxCNC/linuxcnc/pull/1124

**Comment by rockandsalt** [comment]
anybody working on this? I can give this a try.

**Comment by rene-dev** [comment]
I have a branch that builds packages, but not as option but hardcoded.

**Comment by rene-dev** [comment]
This is not required anymore, it has been decided that master will support python3 only once all gtk3 problems are solved.
