### ISSUE TITLE
disable buildbot for legacy releases

### ISSUE THREAD

**Issue by rene-dev** [LinuxCNC/linuxcnc#1162]
should the buildbot be disabled for legacy systems?
There is probably no point if they just fail...
http://buildbot.linuxcnc.org/buildbot/builders/1201.rip-lucid-rtai-i386/builds/7814

https://github.com/LinuxCNC/linuxcnc/commit/323a1e5adc2c11c8ac2367393ef61b0334b4da2a

**Comment by andypugh** [comment]
The buildbot will still build packages for 2.7 (if there are any further releases) or 2.8 for these legacy systems.

**Comment by rene-dev** [comment]
ah, I didnt think about that. thanks.
