### ISSUE TITLE
classicladder not working in current master

### ISSUE THREAD

**Issue by Sigma1912** [LinuxCNC/linuxcnc#1170]
1. Built the current master branch as a rip install. All seems to be successful. 
 2. trying to run a hal file containing loadrt classicladder_rt .. fails with error "file not found"
 3. trying to open classicladder gui with the screen button in gmoccapy settings page fails with error ""Classicladder real-time component not detected"

This is on two different machines that already run rip installs of earlier master branches.

[edit]
Dewey Garrett has been kind enough to look at this and has the given me the following information  that might be helpful:

[quote]
i did a brief test and it is broken in master
probably due to ongoing work by others on gtk3

then i bisected code and found breakage begins at
this commit (make fails) (17day ago):

https://github.com/LinuxCNC/linuxcnc/commit/8c1befade

after that commit, make succeeds but there is no longer
a rule to make bin/classicladdder 
[/quote]

**Comment by andypugh** [comment]
Has this been fixed in the meantime? I just pulled the latest master. 
````make clean
./autogen.sh
./configure --with-realtime=uspace
make
sudo make setuid
halrun
loadrt classicladder_rt
````
And it worked

**Comment by rene-dev** [comment]
whoops, I broke classicladder in gtk3 related buildsystem changes I did. I will fix this tomorrow.
