### ISSUE TITLE
master-gtk3 - gmoccapy edit a program

### ISSUE THREAD

**Issue by gmoccapy** [LinuxCNC/linuxcnc#1176]
- Load gmoccapy
- home machine
- load a program
- click edit loaded program

not possible

- use find and replace to replace a code part
- try to use undo,

not working

Norbert

**Comment by dev-git-usr** [comment]
Hi Norbert,
i can not reproduce the isssue with current master-gtk3

**Comment by rene-dev** [comment]
The branch has been merged, its now all in master.
