### ISSUE TITLE
master-gtk3 - gmoccapy - setting starting dimensions

### ISSUE THREAD

**Issue by gmoccapy** [LinuxCNC/linuxcnc#1178]
- start gmoccapy
- go to settings
- try to set width of window

does not work, the others settings do

**Comment by gmoccapy** [comment]
Just found, that the min value is 1080, do not know why yet. Values bigger that that will change size of window.
Will go on checking

**Comment by hansu** [comment]
I think https://github.com/LinuxCNC/linuxcnc/pull/1557 resolved this.
