### ISSUE TITLE
master-gtk3 - gmoccapy - fullscreen preview not working

### ISSUE THREAD

**Issue by gmoccapy** [LinuxCNC/linuxcnc#1179]
- start gmoccapy
- click fullscreen preview

buttons will move down, but fullscreen preview will not work as it should
just click any of the gremlin button and the screen will update as expected

**Comment by hansu** [comment]
I cannot reproduce this. Maybe this is fixed now?

**Comment by gmoccapy** [comment]
I do not know why, but is fixed on actual release
