### ISSUE TITLE
Carousel. ordinary encoder as sensor + fail to rotate detection

### ISSUE THREAD

**Issue by nik570** [LinuxCNC/linuxcnc#1210]
As Andy Pugh suggested I shouild rise it as an issue.

Ordinary encoder relative/absolute are very common though able to solve using other method carousel component is not very useful with this sensor. If I got it correct what is needed with an incremental encoder is:

   1) Input signal for index pulse, angle not valid until reached so valid signal will make the trick and may also make sense for other sensors.

   2) Parameter number of pockets per turn, guess there also may be chain driven with turns and pockets. so a rational number p/q in mathematical litterature or better expressed for this purpose pockets/turns will probably be a good method.

   3) Parameter angle offset to first pocket.

   4) Output enable rotation, may be connected to unlock and/or relay to rotate.

   5) Parameter distance to turn off backward and forward signals.

   6) Outputs rotate backward and forward signals, it is common both are needed for frequency inverters and also relays. Parameter for delay after enable rotation is turned on?

   7) Output Angular distance to target pocket, make sense then possible to control rotational speed, may be connected to PID regulator in this case. Absolute value may be useful then using backward and forward signal with some frequency inverters but may also be added externally.

   8) Output pocket reached, withing tolerance for amount of time might be a good solution.

   9) Error handling and output signal if not rotating then turned on or other problem.

   10) Enable signal, Jog forward/backward inputs, current position position, homed or OK ready to be used and most probably current state are part of current carousel and still make sense.

   1)1 Ideally input signal for angle s32 should work also then it overflow,  though a little bit theoretic float will eventually lose digits if rotating long enough but wear and aging operator should be more of a problem due to many digits in double.

With my carousel most of the above are useful and guess the same apply for many others. Though only one of the backward/forward signals are needed and do not currently use distance value but would be useful if replacing relay with frequency inverter.

**Comment by andypugh** [comment]
I believe that this function is now available in the latest version of carousel using the "counts" mode. 
(there are also additional deceleration timers and the option to make a final, slower, move to position)
