### ISSUE TITLE
Error: G96 S word missing

### ISSUE THREAD

**Issue by Diekie** [LinuxCNC/linuxcnc#1232]
## Here are the steps I follow to reproduce the issue:

 1.With initial setup of the program, The program runs well, and I can produce a few components, But as soon as I stop the program while it is busy, ( I noticed my tool was blunt / Insert needed to be replaced ) So I stopped the program while it was busy cutting.
 2. Once the Program was stopped during a program, I can't get the program to restart again. It gived a error  ; G96 S word missing
 3. I See another user has the same problem: He says just commanding G97 in MDI, allows you to continue running the same program. I restarted linuxcnc. 
 4. See Link:   https://forum.linuxcnc.org/38-general-linuxcnc-questions/33627-bugs-issues-found-running-a-lathe-in-2-8-0-pre1#102320

## It worked properly before this:
The same program used to work 100% on the last 2.7 distribution

## Information about my hardware and software:

 * I am using this Linux distribution and version: Debian GNU/Linux 9.12 (stretch)
 * I am using this kernel version : Linux debian 4.9.0-12-rt-686-pae #1 SMP PREEMPT RT Debian 4.9.210-1 (2020-01-20)
 * I am running ...
   * [ =>  ] A binary version from linuxcnc.org (including buildbot.linuxcnc.org)
  
 * I am using this LinuxCNC version : 2.8.1 (Same problem on 2.9 pre)
 * I am using this user interface: Axis
 * I am using this interface hardware vendor and chipset : Mesa 6i25 with 7i77 and BSTechBOB

**Comment by andypugh** [comment]
This issue seems to be fixed, though I have asked for a review of the fix.
