### ISSUE TITLE
hal_lighbutton broken in master

### ISSUE THREAD

**Issue by c-morley** [LinuxCNC/linuxcnc#1266]
Seems this may not have  been completed.
I noticed when using sim axis/panelui - it uses hal_lightbuttons.

The buttons don't show and there are errors produced in the terminal.
seems mostly about pango/cario coding

**Comment by rene-dev** [comment]
I have the hsv stuff figured out, there is still a pango issue. I can already see buttons.

**Comment by c-morley** [comment]
Seeing buttons is good! ;) Thanks for working on it - I'm very out of touch with GTK now.
