### ISSUE TITLE
CI on 2.8 branch not working anymore, as ubuntu 16.04 support has ended.

### ISSUE THREAD

**Issue by rene-dev** [LinuxCNC/linuxcnc#1276]
https://github.com/actions/virtual-environments/issues/3287

**Comment by rene-dev** [comment]
I had a quick look, and it does not seem to be possible to install the python2 and gtk2 build dependencies on 20.04

**Comment by andypugh** [comment]
Where does the CI run?

**Comment by rene-dev** [comment]
Its a GitHub action, so probably azure I guess
