### ISSUE TITLE
LCD crashes system calling a page > availible pages

### ISSUE THREAD

**Issue by gmoccapy** [LinuxCNC/linuxcnc#131]
just tested lcd and I found a serious bug

`loadrt lcd fmt_strings="Tool %2d  ZO %7.3f\nX Pos = %8.3f\nY Pos = %8.3f\nZ Pos = %8.3f |Line = %5d\nLength = %5d\nProgress = %3.1f | \n  Machine in ESTOP| \n  Machine ON\n  but not homed"`

My fmt_strings has actually 4 pages, and I can call them with

```
setp lcd.00.page_num 0
setp lcd.00.page_num 1
setp lcd.00.page_num 2
setp lcd.00.page_num 3
```

But if you call setp lcd.00.page_num 4

you get

`rtapi_app: caught signal 11 - dumping core
`

So all crashed, no more reaction etc.

Norbert

**Comment by SebKuzminsky** [comment]
@gmoccapy : I see that you manually inserted @jepler's hal_ready() fix in lcd.c in master, even though he had put the fix in 2.6.  That caused some minor headache when I merged the fix up.

We're trying to use the [Merging Upwards](http://linuxcnc.org/docs/devel/html/code/contributing-to-linuxcnc.html#_use_of_git_in_the_linuxcnc_project) workflow, where fixes go in the oldest active stable branch (currently 2.6), and get merged up to newer stable branches (currently 2.7) and to master.  Putting duplicates of the fixes in master before the merge complicates this process.

Feel free to ask for help if you want someone to do these merges, or to merge it yourself if you feel confident (or ask for help and someone can guide you through the merge process).
