### ISSUE TITLE
Documentation: Language suffix inconsistently with "-" or "_"

### ISSUE THREAD

**Issue by smoe** [LinuxCNC/linuxcnc#1331]
There is this instance of
```
$ ls -l  docs/src/getting-started/running-linuxcnc_es.txt docs/src/getting-started/running-linuxcnc-es.txt
-rw-r--r-- 1 steffen steffen 2050 Sep 23 18:27 docs/src/getting-started/running-linuxcnc-es.txt
-rw-r--r-- 1 steffen steffen 7565 Sep 23 18:27 docs/src/getting-started/running-linuxcnc_es.txt
```
which I read as somehow everyone is confused about what to use. My suggestion is to use the underscore consistently, since many more files adhere to that scheme:
```
steffen@wurzel:~/Github/linuxcnc$ find . -name "*_es.*" | grep -v debian|wc -l
314
$ find docs/ -name "*-es*"
docs/src/getting-started/running-linuxcnc-es.txt
docs/src/getting-started/updating-linuxcnc-es.txt
docs/src/getting-started/about-linuxcnc-es.txt
docs/src/ladder/images/axis_cl-estop.png
docs/src/config/stepper-quickstart-es.txt
docs/src/config/images/switch-no-parallel-es.png
docs/src/config/images/switch-nc-series-es.png
```
Similar for french

```
steffen@wurzel:~/Github/linuxcnc$ find . -name "*_fr.*" | grep -v debian|wc -l
249
steffen@wurzel:~/Github/linuxcnc$ find . -name "*-fr.*" | grep -v debian|wc -l
9
```
And somehow I seem to miss something for the chinese
```
steffen@wurzel:~/Github/linuxcnc$ find . -name "*_cn.*" | grep -v debian|wc -l
5
steffen@wurzel:~/Github/linuxcnc$ find . -name "*-cn.*" | grep -v debian|wc -l
17
```
since the *_cn.pdf is not built for me that is expected by the .desktop file.

**Comment by petterreinholdtsen** [comment]
[Steffen Möller]
> The LinuxCNC community needs to want this first and then this all goes
> very quickly, I am very confident. Another developer meeting would
> help a lot, I think.

I do not really understand what there is to discuss.  Pick the most used
separator and move everything to this one... It further seem obvious to
me these duplicated files need to be merged:

docs/src/config/stepper-quickstart-es.txt
docs/src/config/stepper-quickstart_es.txt
docs/src/getting-started/running-linuxcnc_es.txt
docs/src/getting-started/running-linuxcnc-es.txt
docs/src/getting-started/about-linuxcnc-es.txt
docs/src/getting-started/about-linuxcnc_es.txt
docs/src/getting-started/updating-linuxcnc-es.txt
docs/src/getting-started/updating-linuxcnc_es.txt

I've started on a po4a tool chain for the translation, but have not yet
gotten it to work.  Migrating the existing translation to PO files will
have to be done by someone who understand the language in question, and
might be a lot of work.
-- 
Happy hacking
Petter Reinholdtsen

**Comment by andypugh** [comment]
I suspect that the duplicated files are the result of a merge error. 
Are the files identical? (I am on a work WIndows PC at the moment so can't easily check)

**Comment by smoe** [comment]
docs/src/config/stepper-quickstart*es.txt`are identical. The others not. 
```
-rw-r--r-- 1 steffen steffen 9.8K Sep 23 18:27 docs/src/config/stepper-quickstart-es.txt
-rw-r--r-- 1 steffen steffen 9.8K Sep 23 18:27 docs/src/config/stepper-quickstart_es.txt
-rw-r--r-- 1 steffen steffen 5.8K Sep 23 18:27 docs/src/getting-started/about-linuxcnc-es.txt
-rw-r--r-- 1 steffen steffen 5.3K Sep 23 18:27 docs/src/getting-started/about-linuxcnc_es.txt
-rw-r--r-- 1 steffen steffen 2.1K Sep 23 18:27 docs/src/getting-started/running-linuxcnc-es.txt
-rw-r--r-- 1 steffen steffen 7.4K Sep 23 18:27 docs/src/getting-started/running-linuxcnc_es.txt
-rw-r--r-- 1 steffen steffen 4.0K Sep 23 18:27 docs/src/getting-started/updating-linuxcnc-es.txt
-rw-r--r-- 1 steffen steffen  46K Sep 23 18:27 docs/src/getting-started/updating-linuxcnc_es.txt
```

**Comment by petterreinholdtsen** [comment]
https://github.com/petterreinholdtsen/linuxcnc/tree/translate-po4a contain a draft patch to maintain translations using PO files and po4a.  Consistent naming of translations would make it easier to get this patch working.

**Comment by petterreinholdtsen** [comment]
Here is a quick count of the used separator:

```
% find docs/src/|egrep '[-_](es|fr|cn).txt'|rev|cut -c7|sort|uniq -c|sort -n
     17 -
    177 _
%```

I thus recommend all uses of '-' is replaced with '_'.

**Comment by SebKuzminsky** [comment]
I stepped on @petterreinholdtsen's toes and independently made all the translated docs use "_\<lang>" filenames.
