### ISSUE TITLE
MB2HAL errorcounter does not count high

### ISSUE THREAD

**Issue by andrewheeler82** [LinuxCNC/linuxcnc#1404]
I've been using LinuxCNC for over 10 years now. Starting with the parallel port and now currently on the road with a Mesa 7i96. I run my VFD through MB2HAL and I noticed 2 strange things. I have created a patch for this, maybe the developer of MB2HAL could take a look at it. It's currently working so well for me.
[mb2hal.patch](https://github.com/LinuxCNC/linuxcnc/files/7602166/mb2hal.log)

**Comment by hansu** [comment]
Yeah that makes sense.
I would also increase the error counter here:
```diff
    //set slave id according to each mb_tx
    ret = modbus_set_slave(this_mb_link->modbus, this_mb_tx->mb_tx_slave_id);
    if (ret != 0) {
+       (**this_mb_tx->num_errors)++;

        ERR(this_mb_tx->cfg_debug, "mb_tx_num[%d] mb_links[%d] cannot set slave [%d]",
            this_mb_tx_num, this_mb_tx->mb_link_num, this_mb_tx->mb_tx_slave_id);
        return retOK; //not connected
    }

```

**Comment by andrewheeler82** [comment]
ok that sounds good. The second place where I added the counter. I use it to monitor for broken connections and trigger an emergency stop if the connection is broken. I would like to do more for the LinuxCNC project, but my programming skills are still at the beginning.

**Comment by hansu** [comment]
@andrewheeler82 I propose to open a pull request for this. Then you have a better chance that this change comes into master ;-)

**Comment by andrewheeler82** [comment]
Ok i will Check 😜
