### ISSUE TITLE
mux_generic man page quibbles

### ISSUE THREAD

**Issue by jmkasunich** [LinuxCNC/linuxcnc#143]
The man page for mux_generic describes the following pins:

mux-gen.NN.sel-bitMMM bit in (M=0..N) 
mux-gen.NN.sel-intMMM unsigned in

The sel-bit pin range is actually M=0..log2(N), also M can have at most two digits, so it should be "bitMM" not "bitMMM"

There is only one sel-int pin, so sel-int should not have a trailing MMM

**Comment by jethornton** [comment]
Fixed with commit 1489c8 on 2.7 branch
