### ISSUE TITLE
Documentation - linuxcnc.stat().callLevel is undocumented

### ISSUE THREAD

**Issue by satiowadahc** [LinuxCNC/linuxcnc#1431]
http://linuxcnc.org/docs/devel/html/config/python-interface.html
 `linuxcnc.stat().call_level` is currently Undocumented 

Assuming the documentation from nml_intf/emc_nml.hh is correct:

```c
int callLevel;              // current subroutine level - 0 if not in a subroutine, > 0 otherwise
```

**Comment by c-morley** [comment]
merged commit - Thanks!
