### ISSUE TITLE
uncontrollered move to max limit when F3 (manual) to MDI mode switch

### ISSUE THREAD

**Issue by eginap** [LinuxCNC/linuxcnc#1519]
# The issue tracker is not a support forum

The LinuxCNC issue tracker is to report bugs in the software.
If you have a question about how to use the software, use one of the other methods detailed on our community support page: http://linuxcnc.org/community/

(delete this section before submitting your bug report)

## Here are the steps I follow to reproduce the issue:

 1. press button --> move joint
 2. press MDI mode tab
 3. unpress joint button
 4. then actual position thats joint moves to max limit that all 

## This is what I expected to happen:
stop move untill I unpress button when MDI mode active
## This is what happened instead:

move to limit joint

## Information about my hardware and software:

sim and real hardware repeat these behavior

**Comment by andypugh** [comment]
Which button are you pressing? Which User Interface are you using?

**Comment by eginap** [comment]
AXIS
keyboard buttons for move spindel/ tool /


чт, 20 янв. 2022 г. в 20:56, andypugh ***@***.***>:

**Comment by pcw-mesa** [comment]
That's a pretty bad bug. Maybe disallow mode changes when a jog is in progress?

**Comment by andypugh** [comment]
I just checked with 2.7, and in that case the jog stops when you change to the MDI window.

**Comment by c-morley** [comment]
So you are pressing a holding a jog with keyboard) and at the same time changing to MDI mode with the meyboard?
or same thing but using the mouse to change to MDI?

**Comment by pcw-mesa** [comment]
I duplicated the problem (with 2.9+Axis) 

By keyboard jogging (say pressing the right arrow key) and the changing to
 MDI mode with the mouse. 

Admittedly a strange thing to do but one that causes a hazard. Not sure if 
blocking mode changes while jogging,  aborting jogs in progress on a mode change , 
or suspending jogs in progress when not in manual mode or something entirely 
different is the best solution...

**Comment by andypugh** [comment]
Either clicking with the mouse on the MDI tab, or pressing F5 will leave the system jogging when you release the arrow key.

**Comment by c-morley** [comment]
related to this fix?
https://github.com/LinuxCNC/linuxcnc/issues/691

**Comment by andypugh** [comment]
According to a git bisect the issue was introduced here:
3de8778374bcee0b184c0c4ad04a373585efb7e0

**Comment by andypugh** [comment]
@eginap This issue should be fixed in the next 2.8 release. If you need the fix sooner, then you should be able to get a build from the buildbot an hour or so from now.
