### ISSUE TITLE
Wrong DRO after start up

### ISSUE THREAD

**Issue by gmoccapy** [LinuxCNC/linuxcnc#157]
## Here are the steps I follow to reproduce the issue:

 1. change sim/axis/axis_mm.ini to have home positions at X=50 Y=250 Z=-10 (for Z also change MaxLimit = 0,01 and MINLIMIT = -150
 2. start that config, and home the machine, DRO will now show X=50 Y=250 Z=-10,  this is not the correct position! Default we are in G54. If you do not beleave me, just give on MDI an G0X0Y0Z0, the machine moves to X=54.472 in my case
 3. Now do a G55 and than a G54 OK Now the DRO is correct!

## This is what I expected to happen:
After Homing the DRO should show G54 coordinates, as this is the active coordinate system

## This is what happened instead:
The DRO shows G53 coordinates

## It worked properly before this:
Worked OK prior to PUSH 85210a33609216224373c7235c95551c2986e3c0
from Chris Radek

## Test also with gmoccapy
The test is also possible with gmoccapy, it is easier on that GUI, because you have the offset pages and the DRO changes from machine coordinates over DTG to workpiece coordinate system

I have a lot of people here in germany complaning about the wrong indication.

Norbert

**Comment by cradek** [comment]
Here is what I did to test:

Checked out and built v2.6.12-76-g588b186

I tested changing [AXIS_1]HOME=2.2222 and with G54 Y offset=0, after homing the DRO shows 2.2222 as expected (and shows we are in G54 with G54 Y=0).  I added a G54 Y offset with MDI G10 L2 P1 Y1.  Now after restarting AXIS and homing, the DRO shows G54 Y=1 as expected.  When in Relative mode Y shows 1.2222, when in Machine mode Y shows 2.2222, both as expected.  This is all correct as far as I can tell AFTER commit 85210a3.  It WAS broken as you are describing (or similar) BEFORE commit 85210a3.  Are you sure about this bug report, in particular which revisions are bad and good?  Are my steps to reproduce it wrong?

If I have not reproduced it, please tell exactly what variables to change in the sim/axis/axis_mm.ini file, and exactly what revision you are running.

**Comment by gmoccapy** [comment]
I just tested again with the most recent 2.7 branch, it is still wrong.
I will make a config for you with a step to step instruction to follow that.

Just give me some time!

Meanwhile you can follow my step by step in the first post and you will see that it is not OK!

Norbert

**Comment by cradek** [comment]
I just tried the same tests I described above in v2.7.6-14-gdf183a4 and it also works how I expect, same as described above.  I will wait for more information, thanks.

**Comment by gmoccapy** [comment]
Hallo Chris,

I made some more testing all with the same result, I followed your way and also got wrong DRO, so I went on analysing and after I made a git reset -- hard origin/2.7 a make clean and compiled completely new, the problem was solved.

So the issue is solved. Sorry for reporting "my mixed up repo" instead of a< real bug.

Please close this issue.

Sorry Norbert

**Comment by cradek** [comment]
Thanks, Norbert.  It's so easy to have mixups, no problem.
