### ISSUE TITLE
Halshow: New features (1569) breaks system-wide package installation

### ISSUE THREAD

**Issue by dwrobel** [LinuxCNC/linuxcnc#1588]
Just to not forget about that. See https://github.com/LinuxCNC/linuxcnc/pull/1569#issuecomment-1033951704 for detailed description

**Comment by hansu** [comment]
@dwrobel can you please try with this branch: https://github.com/hansu/linuxcnc/tree/fix-iconpath ?

**Comment by dwrobel** [comment]
> @dwrobel can you please try with this branch: https://github.com/hansu/linuxcnc/tree/fix-iconpath ?

I've just cherry-picked https://github.com/hansu/linuxcnc/commit/709a2c4e3d983320d97ed88dd1e70c16fd35c974 into the current master and it works for me.

Thank you for the fix!
