### ISSUE TITLE
Linuxcncrsh ignores socket open error

### ISSUE THREAD

**Issue by AndyHowell** [LinuxCNC/linuxcnc#1610]
## Here are the steps I follow to reproduce the issue:

 1. Have something listening on port 5007. For example: nc -l 5007
 2. run the testsuite
 3. linuxcncrsh test will hang

This was a local build from git master. It looks like this error has existed for a long time. I'm building on a Ubuntu 21.10.

The patch forces linuxcncrsh to exit with a message that can't open the socket, This allows the test suite to continue. I added code to the test.sh scripts that were hanging. Before starting linuxcncrsh, they check to see if there is something listening on port 5007. If there is, it exits.

[linuxcncrsh.patch.txt](https://github.com/LinuxCNC/linuxcnc/files/8064190/linuxcncrsh.patch.txt)

**Comment by SebKuzminsky** [comment]
Thanks @AndyHowell!  I've applied this to 2.8 and merged to master (2.9)
