### ISSUE TITLE
Halshow did not start halshow_icon.png not found

### ISSUE THREAD

**Issue by andrewheeler82** [LinuxCNC/linuxcnc#1611]
The current master packages from buildbot.linuxcnc.org for Debian Buster do not install the "halshow_icon.png" file. Halshow won't start because of line 37 File not found halshow.tcl. After copying the file by hand, everything works fine.

**Comment by hansu** [comment]
Duplicate (#1588)

**Comment by andrewheeler82** [comment]
Ok sorry

**Comment by hansu** [comment]
No worries 😉
