### ISSUE TITLE
Possible entry missing in documentation for INI RS274 section

### ISSUE THREAD

**Issue by alkabal** [LinuxCNC/linuxcnc#1636]
Hi

Checking other things i have noticed some possible missing option in documentation. 
https://linuxcnc.org/docs/html/config/ini-config.html#sec:rs274ngc-section

LOG_LEVEL
LOG_FILE
DISABLE_G92_PERSISTENCE
DISABLE_FANUC_STYLE_SUB

Best regards

**Comment by andypugh** [comment]
I think you are right. Do you fancy adding them to the docs? Are they relevant to 2.8?
