### ISSUE TITLE
qtDragon, Selection boxes in front of the options on Settings tab are missing

### ISSUE THREAD

**Issue by snelweg** [LinuxCNC/linuxcnc#1767]
Here are the steps I follow to reproduce the issue:

 1. opened the tab [settings]

This is what I expected to happen:
  Selection boxes in front of the options

This is what happened instead:
No selection boxes

It used to work properly a few updates ago.

![Screenshot_2022-06-16_13-55-57](https://user-images.githubusercontent.com/1257901/174064744-283af0b6-b6a8-477d-b653-01ab37509844.png)

Information about my hardware and software:

 * I am using this Linux distribution and version (often, shown by `lsb_release -a`):
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

 * I am using this kernel version (shown by `uname -a`):
 Linux cnc-machine 4.19.0-20-rt-amd64 #1 SMP PREEMPT RT Debian 4.19.235-1 (2022-03-17) x86_64 GNU/Linux

 * I am running ...
   * [ ] A binary version from linuxcnc.org (including buildbot.linuxcnc.org)
   * [ ] A binary I built myself
   * [ ] A binary version from some other source besides linuxcnc.org
   * [X] the apt version, 
   ** deb     http://buildbot.linuxcnc.org/ buster master-rtpreempt
   ** deb-src http://buildbot.linuxcnc.org/ buster master-rtpreempt

 * I am using this LinuxCNC version (shown in package manager or, for git versions, `scripts/get-version-from-git`):
 LINUXCNC - 2.9.0-pre0-6687-g3bbfd0017

 * I am using this user interface (GUI) (e.g., AXIS, Touchy, gmoccapy, etc):
 qtDragon
 * I am using this interface hardware vendor and chipset (e.g., parallel port, ethernet port, FPGA card): 
  Mesa 7i96, 7i84

**Comment by c-morley** [comment]
Is problem this just in this theme?

**Comment by snelweg** [comment]
It happens in qtDragon_hd too

**Comment by c-morley** [comment]
Yes but just the argentium style?
I pushed a fix for both qtdragon and dragon_hd

**Comment by snelweg** [comment]
I have to check at my machine, will be there tomorrow. Thanks

**Comment by c-morley** [comment]
Any update?

**Comment by snelweg** [comment]
Oops, yes there is an update. The machine that uses the apt method of updating works. The other machine (buildbot) does not.
I have taken a rest from LinuxCNC, after updating my production machine everything stopped working. Maybe next week I will spend some more time on it.

**Comment by c-morley** [comment]
I think these are fixed. i will close the issues. please reopen if the problems persists.
