### ISSUE TITLE
qtDragon, camera stopped working

### ISSUE THREAD

**Issue by snelweg** [LinuxCNC/linuxcnc#1768]
Here are the steps I follow to reproduce the issue:

 1. opened the tab [camera]

This is what I expected to happen:
 A view from my camera mounted on the spindle

This is what happened instead:
Nothing. There was an error message though.
'[QTvcp.QTVCP.WIDGETS.CAMVIEW_WIDGET][ERROR]  Video capture error: VideoCapture() takes at most 1 argument (2 given) (camview_widget.py:290)
'

It used to work properly a few updates ago.

Information about my hardware and software:

 * I am using this Linux distribution and version (often, shown by `lsb_release -a`):
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

 * I am using this kernel version (shown by `uname -a`):
 Linux cnc-machine 4.19.0-20-rt-amd64 #1 SMP PREEMPT RT Debian 4.19.235-1 (2022-03-17) x86_64 GNU/Linux

 * I am running ...
   * [ ] A binary version from linuxcnc.org (including buildbot.linuxcnc.org)
   * [ ] A binary I built myself
   * [ ] A binary version from some other source besides linuxcnc.org
   * [X] the apt version, 
   ** deb     http://buildbot.linuxcnc.org/ buster master-rtpreempt
   ** deb-src http://buildbot.linuxcnc.org/ buster master-rtpreempt

 * I am using this LinuxCNC version (shown in package manager or, for git versions, `scripts/get-version-from-git`):
 LINUXCNC - 2.9.0-pre0-6687-g3bbfd0017

 * I am using this user interface (GUI) (e.g., AXIS, Touchy, gmoccapy, etc):
 qtDragon
 * I am using this interface hardware vendor and chipset (e.g., parallel port, ethernet port, FPGA card): 
  Mesa 7i96, 7i84

**Comment by c-morley** [comment]
Looks like the library function signature has been changed - I switched to newer version recently.
I can add a fallback to old version.

**Comment by snelweg** [comment]
Ok, great. Would be nice to have it working again.
Another question about the cameraview I habe is that it doesn't work when a job is processing. In gmoccapy I can watch the spindle bit doing its work. But in qtDragon I can not switch to the cameraview tab. I watch the processing from behind my workstation, I use VNC for that, so it is very useful to be able to see the stock and bit as they are processed.

**Comment by c-morley** [comment]
Ok I pushed a fix for the camera. I have code to allow camerra,setup and gcode pages to be delectable in auto mode. I'll push it soon.

**Comment by snelweg** [comment]
Great!

**Comment by c-morley** [comment]
I pushed it now so let me know if you like it.

**Comment by snelweg** [comment]
ok, thanks!
Thanks for updating the documentation!
