### ISSUE TITLE
qtDragon, pdf viewer does not show setup file anymore

### ISSUE THREAD

**Issue by snelweg** [LinuxCNC/linuxcnc#1769]
FreeCAD path can generate a setup file from the path jobs. This is an PDF file with the same name as the gcode file just another extension. This is perfect for remembering what tools to get ready and such. 

Here are the steps I follow to reproduce the issue:
 1 opened the gcode file
 2    opened the tab [pdf]

This is what I expected to happen:
the  pdf  setup file to show

This is what happened instead:
Nothing. There was an error message though.
'[QTvcp.QTVCP.LIB.QT_PDF.PDFVIEWER][WARNING]  Sample setup_tab, does not exists at: /usr/lib/python3/dist-packages/qtvcp/lib/qt_pdf/setup_tab.pdf (PDFViewer.py:35)

'

It used to work properly a few updates ago.

Information about my hardware and software:

    I am using this Linux distribution and version (often, shown by lsb_release -a):
    Distributor ID: Debian
    Description: Debian GNU/Linux 10 (buster)
    Release: 10
    Codename: buster

    I am using this kernel version (shown by uname -a):
    Linux cnc-machine 4.19.0-20-rt-amd64 

https://github.com/LinuxCNC/linuxcnc/pull/1 SMP PREEMPT RT Debian 4.19.235-1 (2022-03-17) x86_64 GNU/Linux

I am running ...

A binary version from linuxcnc.org (including buildbot.linuxcnc.org)
A binary I built myself
A binary version from some other source besides linuxcnc.org
the apt version,
** deb http://buildbot.linuxcnc.org/ buster master-rtpreempt
** deb-src http://buildbot.linuxcnc.org/ buster master-rtpreempt

I am using this LinuxCNC version (shown in package manager or, for git versions, scripts/get-version-from-git):
LINUXCNC - 2.9.0-pre0-6687-g3bbfd0017

I am using this user interface (GUI) (e.g., AXIS, Touchy, gmoccapy, etc):
qtDragon

I am using this interface hardware vendor and chipset (e.g., parallel port, ethernet port, FPGA card):
Mesa 7i96, 7i84

**Comment by c-morley** [comment]
I fixed the missing default PDF file but I'm not sure why that would stop it from loading a specified PDF.
When this last worked did it launch it's own window or did it use the tab?

**Comment by snelweg** [comment]
it used the tab

**Comment by c-morley** [comment]
I think these are fixed. I will close the issues. please reopen if the problems persists.
