### ISSUE TITLE
Forgetting G64 mode after E-stop

### ISSUE THREAD

**Issue by propcoder** [LinuxCNC/linuxcnc#177]
## Here are the steps I follow to reproduce the issue:

Open sim axis_mm config.
Edit a copy of axis.ngc example file and remove G64 in line number 10.
Run the program. Observe liveplot - TP rounds the corners.
Execute G61 in MDI.
Run the program again - TP does not round the corners.
Hit F1 (E-stop).
Run the program again - TP rounds the corners.

This issue might influence similar behaviour after startup, when Estop HAL pin is used and in INI:
RS274NGC_STARTUP_CODE = G61
or
RS274NGC_STARTUP_CODE = G64 P0.1 Q0.001
Do not forget to open modified axis.ngc file while testing.
## This is what I expected to happen:

G61 / G64 mode retained, including G64 P and Q parameters.
## This is what happened instead:

G61 / G64 modes are lost.
# Using LinuxCNC 2.7.7

**Comment by zultron** [comment]
I have a unit test for this [here][1].  I'm looking at solving this problem with state tags, and will be discussing over at #134.

[1]: https://github.com/zultron/machinekit/tree/unit-test-177-lcnc
