### ISSUE TITLE
PNCconf - add Mesa - specify "logical number"  

### ISSUE THREAD

**Issue by zz912** [LinuxCNC/linuxcnc#1832]
I am trying to add another tab to PNCconf.
1) I can't find the definition of "logic number" anywhere.
File /home/zdenek/linuxcnc/linuxcnc-2.8/src/emc/usr_intf/pncconf/private_data.py:
![private_data-py](https://user-images.githubusercontent.com/96618597/178674576-4a3ff6af-30f9-48a8-b6fd-8f1fd9bd3340.png)
I dont know how correctly logic number use.

2) Perhaps the parameters of the 7i96 card are incorrectly defined. I didn't really understand what PCW wanted to tell me.
https://forum.linuxcnc.org/27-driver-boards/46356-can-i-use-7i96s-with-lcnc-2-8?start=10#247126
https://forum.linuxcnc.org/27-driver-boards/46356-can-i-use-7i96s-with-lcnc-2-8?start=10#247183
I dont know what is SB number

**Comment by silopolis** [comment]
Le mer. 13 juil. 2022 à 09:22, zz912 ***@***.***> a écrit :

> I am trying to add another tab to PNCconf.
>

Don't know what's your project but do you know @jetthornton 's MesaCT?

https://github.com/jethornton/mesact

I'd have a look before investing time...

**Comment by zz912** [comment]
I am trying to add 7i96s to LCNC 2.8. If I managed to do it, only the extended input options of the InM Input Module would not work.

JT Configurator is not part of LCNC 2.8 and cannot configure for 7i96s+LCNC 2.8

**Comment by c-morley** [comment]
The number represents whether the GPIOI can be changed at run time or not. 0 = run time changes allowed, 100 means no runtime changes.

here is an example of the numbers use in the code:
https://github.com/LinuxCNC/linuxcnc/blob/2.8/src/emc/usr_intf/pncconf/pncconf.py#L2960

**Comment by zz912** [comment]
What "run time" mean?

I thought that:
number<100 
means some automatic mod
If it was an automatic mode. Is this mod related to the -"max GPIOI" parameter?

number>100 
means some automatic mod

I found that when GPIOI was number 0, I could not change it to GPIOO or to S.STEPB. If I changed the number to 100, the change appeared in PNCconf.

However, I don't like doing something where I don't know the essence of the problem. That's why I asked this question.

but my theory not coresponded with example:
`["7i64", "7i64", 0,[_("7i64-Input\nP3 and P4"),_("7i64-Output\nP2 and P5"),_("7i64-Analog In")], 0,0,0,0,0,0,0,0,
        [S.GPIOI,100],[S.GPIOI,100],[S.GPIOI,100],[S.GPIOI,100],[S.GPIOI,100],[S.GPIOI,100],
        [S.GPIOI,100],[S.GPIOI,100],[S.GPIOI,100],[S.GPIOI,100],[S.GPIOI,100],[S.GPIOI,100],
        [S.GPIOI,100],[S.GPIOI,100],[S.GPIOI,100],[S.GPIOI,100],[S.GPIOI,100],[S.GPIOI,100],
        [S.GPIOI,100],[S.GPIOI,100],[S.GPIOI,100],[S.GPIOI,100],[S.GPIOI,100],[S.GPIOI,100],
        [S.GPIOO,100],[S.GPIOO,100],[S.GPIOO,100],[S.GPIOO,100],[S.GPIOO,100],[S.GPIOO,100],
        [S.GPIOO,100],[S.GPIOO,100],[S.GPIOO,100],[S.GPIOO,100],[S.GPIOO,100],[S.GPIOO,100],
        [S.GPIOO,100],[S.GPIOO,100],[S.GPIOO,100],[S.GPIOO,100],[S.GPIOO,100],[S.GPIOO,100],
        [S.GPIOO,100],[S.GPIOO,100],[S.GPIOO,100],[S.GPIOO,100],[S.GPIOO,100],[S.GPIOO,100],
        [S.ANALOGIN,0],[S.ANALOGIN,1],[S.NUSED,0],[S.NUSED,0],[S.NUSED,0],[S.NUSED,0],
        [S.NUSED,0],[S.NUSED,0],[S.NUSED,0],[S.NUSED,0],[S.NUSED,0],[S.NUSED,0],
    [S.NUSED,0],[S.NUSED,0],[S.NUSED,0],[S.NUSED,0],[S.NUSED,0],[S.NUSED,0],[S.NUSED,0],[S.NUSED,0],[S.NUSED,0],[S.NUSED,0],[S.NUSED,0],[S.NUSED,0],
    [S.NUSED,0],[S.NUSED,0],[S.NUSED,0],[S.NUSED,0],[S.NUSED,0],[S.NUSED,0],[S.NUSED,0],[S.NUSED,0],[S.NUSED,0],[S.NUSED,0],[S.NUSED,0],[S.NUSED,0] ],`
What mean, when a lot of number = 100?

**Comment by c-morley** [comment]
On some cards the GPIO can be changed to input or output when you start linuxcnc (run time).
Others can't be changed at all - always input or always output.
0 = can be changed
100 = can't be changed

In your sample above the 100s mean all the GPIOI can only by input and all the GPIOO can be only be Output)

**Comment by zz912** [comment]
Why is the number 100 and 0 sometimes used and sometimes the number represents the pin number?

**Comment by c-morley** [comment]
GPIO is special - they only use 0 or 100 
For other components the number represents logical number

**Comment by zz912** [comment]
I think I already know how "logic number" works. Can I ask about the "max GPIO" parameter? Can use for example GPIOI 124?

**Comment by c-morley** [comment]
max GPIO is just the maximum number of GPIO available on the card.
On some cards you can 'turn off' the other components such as step generators to gain GPIO.
This number is if all the optional components were turned off, how many GPIO are available.

GPIOI 124 would be accepted but would just be the same as GPIOI 100, without more code changes.

**Comment by phillc54** [comment]
> On 16 Jul 2022, at 3:27 am, c-morley ***@***.***> wrote:
> 
> 
> The number represents whether the GPIOI can be changed at run time or not. 0 = run time changes allowed, 100 means no runtime changes.
> 
> here is an example of the numbers use in the code:
> https://github.com/LinuxCNC/linuxcnc/blob/2.8/src/emc/usr_intf/pncconf/pncconf.py#L2960 <https://github.com/LinuxCNC/linuxcnc/blob/2.8/src/emc/usr_intf/pncconf/pncconf.py#L2960>
Thanks Chris, that is something I did not previously know. I think this means that the 7i96 GPIO in Tab 1 need to be all changed to [S.GPIOI, 100]

Cheers, Phill

**Comment by c-morley** [comment]
Phill - all the GPIO on the 7i96 cannot be changed at runtime?

For completenes I see the SSR0 combines the 0,100 with logical number.
ie 100 would be a unchangable  logical 0 SSR
101 would be a unchangable  logical 1 SSR

It's probably what should have been done with the GPIO

**Comment by phillc54** [comment]
There are 11 inputs and 6 outputs (SSR) on TB3 (tab1)

There are also 17 i/o on the P1 expansion header (tab3)

Attached is the pin file

**Comment by zz912** [comment]
> On some cards the GPIO can be changed to input or output when you start linuxcnc (run time).

Does it have any practical use?

**Comment by zz912** [comment]
I wrote the rules for logical number:

# logical number (shortly number)
# If number < 100 => GPIO can be changed to GPIOO or GPIOD after start LinuxCNC (run time)
# If number > 100 => GPIO can NOT be changed to GPIOO or GPIOD after start LinuxCNC (always input or always output)
# Value of number or number-100 corresponds with HAL Pin of Hostmot2 component
# The number 0 or 100 can be repeated only for GPIO and the numbering is done automatically

Are these rules correct?
Can I add this to private_data.py and ADDING_A_MESA_CARD.md ?

**Comment by c-morley** [comment]
> > On some cards the GPIO can be changed to input or output when you start linuxcnc (run time).
> 
> Does it have any practical use?

Yes you can modify the number of input or output based on your needs with out having to modify the firmeware.

**Comment by c-morley** [comment]
* GPIOD after start LinuxCNC (run time)  ->      _at_ the start of linuxcnc, load time if you prefer

**Comment by zz912** [comment]
Is it other rule?
how is defined the load time?

**Comment by c-morley** [comment]
you can change GPIO __at__ starttup  not __after__ starting linuxcnc (on some boards)
older boards used to load the firmware every time it started, so you can have more control on how it set it's self up.
newer boards have the firmware held in eeprom and have extra hardware on the board that doesn't allow as much flexibility.

**Comment by zz912** [comment]
Ok I get it. I transformed rules:
`# logical number (shortly number)
# If number < 100 => GPIO can be changed to GPIOO or GPIOD at the start of linuxcnc, load time if you prefer (run time)
# If number > 100 => GPIO can NOT be changed to GPIOO or GPIOD at the start of linuxcnc, load time (always input or always output)
# Value of number or number-100 corresponds with HAL Pin of Hostmot2 component
# The number 0 or 100 can be repeated only for GPIO and the numbering is done automatically`

**Comment by c-morley** [comment]
pull request was merged - I';m closing this ticket. Thank you.
