### ISSUE TITLE
Ask for 2.8.3 version

### ISSUE THREAD

**Issue by zz912** [LinuxCNC/linuxcnc#1838]
I would like to request the release of version 2.8.3.
Contains FIXES that are in 2.8
The most important FIX for me is this:
https://forum.linuxcnc.org/gmoccapy/43045-after-saving-ngc-file-ask-for-do-you-want-to-exit-without-saving-the-changes
This fix will make many people happy because this BUG is very annoying.

I tried to add the 7i96s card to the stable version 2.8, but it didn't work.
https://github.com/LinuxCNC/linuxcnc/issues/1832
Nobody knows how "logic number" works.

I also created the Czech language for Gmoccapy, but I couldn't put it on Github.
/home/zdenek/linuxcnc/linuxcnc-2.8/src/po/gmoccapy/cs.po
[cs.po.txt](https://github.com/LinuxCNC/linuxcnc/files/9121657/cs.po.txt)

**Comment by hansu** [comment]
I can help you adding your language when I am back from vacation ;-)

**Comment by zz912** [comment]
Enjoy your vacation. C-morley help me with understooding pncconf now.

**Comment by hansu** [comment]
>I can help you adding your language when I am back from vacation ;-)

It was more aimed for adding the cs.po file.
But as I see you are now familiar with creating pull requests, so I think you just create one when you have finished your translation .:slightly_smiling_face:

**Comment by zz912** [comment]
> > I can help you adding your language when I am back from vacation ;-)
> 
> It was more aimed for adding the cs.po file. But as I see you are now familiar with creating pull requests, so I think you just create one when you have finished your translation .slightly_smiling_face

I've already done it.

**Comment by smoe** [comment]
This can now be closed since 2.8.3 is out?

**Comment by zz912** [comment]
Yes, it can be closed.

**Comment by hansu** [comment]
A bit unfortunate that your translation work didn't make it into the 2.8.3 release, but I was also a bit surprised by the release date.

**Comment by smoe** [comment]
Feels like there will be a 2.8.4 to me.

**Comment by zz912** [comment]
Date relase was big suprise.  On the one hand, I am glad that it was created. On the other hand, there could be a notification that this session will be created, for example, 14 days in advance.

**Comment by andypugh** [comment]
I announced that is was happening in the online meeting. In fact it was a few days later than I said.

**Comment by zz912** [comment]
This Issue was something like a wishlist. Will version 2.8.4 be planned?

**Comment by hansu** [comment]
>I announced that is was happening in the online meeting. In fact it was a few days later than I said.

Sure, but it didn't sound to me that it will have been done the day after :smile:
