### ISSUE TITLE
LinuxCNC 2.8.3 - wrong web description

### ISSUE THREAD

**Issue by zz912** [LinuxCNC/linuxcnc#1927]
I looked at website:
![release_2-8-3](https://user-images.githubusercontent.com/96618597/184550622-8788f78e-43e2-47f3-97b5-00d61c7bb635.png)

It is not true:
![2-8-3_7i96s](https://user-images.githubusercontent.com/96618597/184550655-cf739385-a618-4541-9624-b045563ae654.png)

I would like to recap the situation with the 7i96s card.

1) PCW made a 7i96s card for LCNC version 2.9
2) Mr. phillc54 made commit for LCNC 2.8 + 7i96s
It was a mistake because he didn't know that LCNC 2.8 had the old hostmot2
https://github.com/LinuxCNC/linuxcnc/issues/1872
3) Mr. phillc54 uncommit for LCNC 2.8 + 7i96s
4) I didn't like that the 7i96s card is only for non-stable LCNC 2.9 and I made an imperfect configuration for LCNC 2.8 + 7i96s
https://github.com/LinuxCNC/linuxcnc/pull/1897
5) At the same time, a commit was created to update hostmot2
https://github.com/LinuxCNC/linuxcnc/pull/1899
6) If hostmot2 is updated, my imperfect configuration for LCNC 2.8 + 7i96s will disappear and Mr . phillc54 restores what he undid.

**Comment by silopolis** [comment]
Sorry missed it 😬
May be better directed to LinuxCNC/wlo repository.

**Comment by zz912** [comment]
What is wlo? What wlo mean?

**Comment by silopolis** [comment]
Le mar. 13 sept. 2022 à 19:27, zz912 ***@***.***> a écrit :

> What is wlo? What wlo mean?
>

https://github.com/LinuxCNC/wlo

Www.Linuxcnc.Org

**Comment by zz912** [comment]
Thank you. This is exactly what i wanted.
