### ISSUE TITLE
Python interface - stat.velocity does not return value

### ISSUE THREAD

**Issue by gmoccapy** [LinuxCNC/linuxcnc#202]
According to master documentation of the python interface 

stat.velocity should return the ini value of [TRAJ] DEFAULT_VELOCITY, but it returns zero on every circumstance.

Norbert

**Comment by gmoccapy** [comment]
If that should not be used, we should take the attribute out of the documentation, not say, it has no usefull function. If it not usefull, get rid of it!

Norbert

**Comment by jepler** [comment]
please feel free to do as you think is best in this matter.
