### ISSUE TITLE
docs: LinuxCNC_Documentation.pdf - double chapter

### ISSUE THREAD

**Issue by tseufl** [LinuxCNC/linuxcnc#204]
In the pdf output of the docs a chapter is duplicated (see picture below).

in:
 -> linuxcnc/docs/src/Master_Documentation.txt <-
line 17-19:

17 = LinuxCNC History
18
19 include::common/emc-history.txt[]

Here is a chapter title (= LinuxCNC History) and the following doc (emc-history.txt) also contains exactly the same title (for html and pdf-output)

This seems to me to be the cause.

Changing the title in emc-history.txt is not a good idea, because then the html and pdf output can cause problems (with all interrelated internal links).
My idea to solve the problem would be to modify the chapter title in linuxcnc/docs/src/Master_Documentation.txt something so that they are no longer exactly the same.

![linuxcnc_documentation](https://cloud.githubusercontent.com/assets/22623668/19778378/b3534cc4-9c7c-11e6-8c6b-51b90f672175.png)

**Comment by jethornton** [comment]
I don't see the double title in master or 2.7

**Comment by SebKuzminsky** [comment]
This was fixed in d0b5fd91a146d4fcf02cbf01fff2c5f8adb3fc32 (in 2.7.8 and later).
