### ISSUE TITLE
docs: man9 / hostmod 2.9 - broken/wrong links

### ISSUE THREAD

**Issue by tseufl** [LinuxCNC/linuxcnc#206]
in:
 linuxcnc/docs/man/man9/hostmot2.9 
line 1002+1017
-> 2 broken/wrong links (=>  http://linuxcnc.org/docs/html/hal_comp.html  [as plain text])

**Comment by jethornton** [comment]
Does it make sense to change the name of the chapter from comp.txt to halcompile.txt before fixing the broken link?

JT

**Comment by jethornton** [comment]
Link and man page reference fixed.
