### ISSUE TITLE
QTVCP Versa Probe Widget missing butting connections

### ISSUE THREAD

**Issue by ihabmmali** [LinuxCNC/linuxcnc#2078]
@c-morley  The versa_probe.py file under qtvcp/widgets is missing the following code at line 77:

        self.pbtn_set_x.released.connect(self.pbtn_set_x_released)
        self.pbtn_set_y.released.connect(self.pbtn_set_y_released)	
        self.pbtn_set_z.released.connect(self.pbtn_set_z_released)
        self.pbtn_set_angle.released.connect(self.pbtn_set_angle_released)

Basically the set X,Y,Z, and Angle buttons are unconnected in widget class. Just wanted to let you know. 

## Information about my hardware and software:

 * I am using this Linux distribution and version (often, shown by `lsb_release -a`):
 * I am using this kernel version (shown by `uname -a`):
 * I am running ...
   * [ ] A binary version from linuxcnc.org (including buildbot.linuxcnc.org)
   * [ ] A binary I built myself
   * [ ] A binary version from some other source besides linuxcnc.org
 * I am using this LinuxCNC version (shown in package manager or, for git versions, `scripts/get-version-from-git`):
 * I am using this user interface (GUI) (e.g., AXIS, Touchy, gmoccapy, etc):
 * I am using this interface hardware vendor and chipset (e.g., parallel port, ethernet port, FPGA card):

**Comment by c-morley** [comment]
Thank you - pushed the fix to master.
