### ISSUE TITLE
Errors in Python code that is called via G-Code cause Boost Python Crashes (linux boost::python::error_already_set)

### ISSUE THREAD

**Issue by snowgoer540** [LinuxCNC/linuxcnc#2092]
`## Here are the steps I follow to reproduce the issue:

1. create a .ngc file with the following two lines (with an intentional error (the space after the comma)):
;py, print(2*3)
m30

## This is what I expected to happen:
Previous to commit ac779c4 the following error would be shown in a popup:

"Near line 2 of /home/plasma/linuxcnc/nc_files/pytest.ngc:
py_execute( print(23)):
IndentationError: ('unexpected indent', ('', 1, 1, ' print(23)\n'))"

## This is what happened instead:
Linuxcnc crashes with the following error:

"terminate called after throwing an instance of 'boost::python::error_already_set'
/home/plasma/linuxcnc-dev/scripts/linuxcnc: line 930: 29799 Aborted $EMCDISPLAY -ini "$INIFILE" $EMCDISPLAYARGS $EXTRA_ARGS"

## It worked properly before this:
commit 1efe486 is the commit before commit ac779c4, it works properly when commit 1efe486 is checked out.

## Information about my hardware and software:

 * I am using this Linux distribution and version (often, shown by `lsb_release -a`):  master
 * I am using this kernel version (shown by `uname -a`): "Linux mx 4.19.0-21-rt-amd64 #1 SMP PREEMPT RT Debian 4.19.249-2 (2022-06-30) x86_64 GNU/Linux`
 * I am running ...
   * [x ] A compiled run in place version
 * I am using this LinuxCNC version (shown in package manager or, for git versions, `scripts/get-version-from-git`): v2.9.0-pre0-8016-gb7f86c2022
 * I am using this user interface (GUI) (e.g., AXIS, Touchy, gmoccapy, etc): Axis
 * I am using this interface hardware vendor and chipset (e.g., parallel port, ethernet port, FPGA card): Happens on BM or VM hardware.

Steps to recreate, mentioned in the comments section of ac779c4 commit:

1. create a .ngc file with the following two lines (with an intentional error (the space after the comma)):
;py, print(2*3)
m30

2. Checkout commit https://github.com/LinuxCNC/linuxcnc/commit/1efe486baf9fa435b629fb13030da60c812aa257

3. make clean

4. make

5. When it's done compiling, run linuxcnc and choose the axis simulation

6. Navigate to the .ngc file created in step 1 and load it.

7. Axis will throw a popup with the following error (linuxcnc will not crash):
Near line 2 of /home/plasma/linuxcnc/nc_files/pytest.ngc:
py_execute( print(23)):
IndentationError: ('unexpected indent', ('', 1, 1, ' print(23)\n'))

8. Close linuxcnc and checkout commit https://github.com/LinuxCNC/linuxcnc/commit/ac779c49b350bc88c27fac226cb4d45be85bbe1d

9. make clean

10. make

11. When it's done compiling, run linuxcnc and choose the axis simulation

12. Navigate to the .ngc file created in step 1 and load it.

13 linuxcnc will crash with the following error:
terminate called after throwing an instance of 'boost::python::error_already_set'
/home/plasma/linuxcnc-dev/scripts/linuxcnc: line 930: 29799 Aborted $EMCDISPLAY -ini "$INIFILE" $EMCDISPLAYARGS $EXTRA_ARGS

**Comment by c-morley** [comment]
Just to bring it to Jeff's attention, next time he is around.
