### ISSUE TITLE
uspace+rtai does not provide rate monotonic scheduling, apparently

### ISSUE THREAD

**Issue by jepler** [LinuxCNC/linuxcnc#2098]
In a VM with 4.19.195-rtai-amd64 configured for uspace+rtai I get occasional (less than 1 in 50) failures in threads.0, the test which is intended to reveal lapses in rate-monotonic-scheduling
```line 937: got 0, expected 10 or 1```

**Comment by andypugh** [comment]
Can you define "rate monotonic scheduling"? 

I know what the words mean, but not what them mean in that combination.

**Comment by jepler** [comment]
For correctness, we depend on the *fast* thread never being interrupted by the *slow* thread. This is important to just two components, but without it they will work erratically: the software stepgen & software encoder.

**Comment by andypugh** [comment]
Thanks
