### ISSUE TITLE
.deb: Cannot find the linuxcnc Python module

### ISSUE THREAD

**Issue by smoe** [LinuxCNC/linuxcnc#2226]
Without that module, any "import linuxcnc" fails in Python. Any idea anyone?

In our source tree, it is located in lib/python/, so to help myself I just bent PYTHONPATH to my local build, worked, but ... am I missing something?

@petterreinholdtsen ?

Thanks!
Steffen

**Comment by petterreinholdtsen** [comment]
[Steffen Möller]
> Without that module, any "import linuxcnc" fails in Python. Any idea
> anyone?

I see it using 'dpkg -L linuxcnc-uspace|grep -i dist-packages'.  Is it
not there on your machine?

-- 
Happy hacking
Petter Reinholdtsen

**Comment by smoe** [comment]
I eventually found
`/usr/lib/python3/dist-packages/linuxcnc.cpython-310-x86_64-linux-gnu.so`
and on a new day in a test script the "import linuxcnc" just works.
Thank you!

**Comment by SebKuzminsky** [comment]
Possibly a python version mismatch, 3.9 vs 3.10?
