### ISSUE TITLE
PNCconf - delete tool.tbl during modification  configuration

### ISSUE THREAD

**Issue by zz912** [LinuxCNC/linuxcnc#2257]
I would like to request that the tool.tbl file generated by PNCconf behaves the same as the custom.hal file. I would need PNCconf to create a tool.tbl file during the first configuration, but not overwrite the tool.tbl file when modifying an already created configuration. It's annoying that I have to refresh the tool table after every machine configuration modification.

**Comment by c-morley** [comment]
Ya that seems reasonable - I'll see what I can do.

**Comment by c-morley** [comment]
ok this should be fixed now.

**Comment by zz912** [comment]
I wanted test it, but PNCconf doesnt work now:
 
![PNCconf-error-001](https://user-images.githubusercontent.com/96618597/212530161-52e23c1a-68a2-453b-a725-f89a04138de9.png)
![PNCconf-error-002](https://user-images.githubusercontent.com/96618597/212530162-62d15c56-37be-474a-9ea8-bc1dfed7e96b.png)
![PNCconf-error-003](https://user-images.githubusercontent.com/96618597/212530163-09415739-0780-4136-bf32-8536ae3c79aa.png)
![PNCconf-error-004](https://user-images.githubusercontent.com/96618597/212530166-264885ff-1087-48b6-97c4-46af670fa047.png)
![PNCconf-error-005](https://user-images.githubusercontent.com/96618597/212530167-b77f0490-4349-477f-b026-a4411c8de21c.png)
![PNCconf-error-006](https://user-images.githubusercontent.com/96618597/212530168-97cd2e36-1b99-4a92-af2a-44697afbab59.png)

**Comment by zz912** [comment]
I made new test with old Mesa card 7i96 not with 7i96s and I found that PNCconf works.

I tested overwriting tool.tbl and verified that it works.

Therefore, I would like to thank you for this modification and hereby close this Issue.
