### ISSUE TITLE
Linuxcnc configuration failes if python2.7 is not default in Gentoo->error: Python version too old (2.7 or newer required)

### ISSUE THREAD

**Issue by Petross404** [LinuxCNC/linuxcnc#226]
`$python -V
 Python 3.5.2` 
When I ran
`./configure`` --with-realtime=uspace --enable-non-distributable=yes --with-boost-python=boost_python-2.7
`
`
checking python version...   File "<string>", line 1
    import sys;raise SystemExit,sys.hexversion<0x2070000
                               ^
SyntaxError: invalid syntax
configure: error: Python version too old (2.7 or newer required)`

If I select python2.7 as the default, the configuration completes without error. The thing is I want portage to work with python3.5, so defaulting to python2.7 isn't an option for some users (including me).

All the best

**Comment by jepler** [comment]
LinuxCNC requires Python 2.7.  It is not compatible with 3.x, and no one has offered to undertake the porting effort.

Try specifying --with-python=<path to python 2.7 interpreter> to configure; if this is broken, then it's a problem we would like to fix.
