### ISSUE TITLE
2.8 Conversion Script Bug

### ISSUE THREAD

**Issue by jethornton** [LinuxCNC/linuxcnc#229]
If the 2.7 configuration doesn't have [DISPLAY]MAX_LINEAR_VELOCITY OR [TRAJ]MAX_LINEAR_VELOCITY the script fails to add it. This causes a silent error that can only be seen if you run linuxcnc from a terminal window.

**Comment by andypugh** [comment]
What should the script guess as the new value? I think I might have considered this and not found an answer.

**Comment by jethornton** [comment]
You could pick the highest one or ask the user what they want.

**Comment by andypugh** [comment]
I believe this to be fixed
http://git.linuxcnc.org/gitweb?p=linuxcnc.git;a=commit;h=cb9dc755d23157b6156f5901b402e81252bc8e57
