### ISSUE TITLE
following error when homing with abs encoder

### ISSUE THREAD

**Issue by annhan** [LinuxCNC/linuxcnc#2308]
Hi.

This error occurred when I clicked home on any axis, which was configed to be the abs encoder.

HOME_ABSOLUTE_ENCODER	= 2

## Ini file of joint

```
[JOINT_0]
#AXIS = X
NAME = shoulder
TYPE = ANGULAR
MAX_VELOCITY = 100
MAX_ACCELERATION = 80.0
P = 2.0
I = 0.0
D = 0.0
FF0 = 0.0
FF1 = 1
FF2 = 0.00030
BIAS = 0.0
DEADBAND = 0.2
MAX_OUTPUT = 0.0
STEPGEN_MAX_VEL =    150
STEPGEN_MAX_ACC =    300
BACKLASH =           0.0
MIN_LIMIT = -181
MAX_LIMIT = 181
HOME_IGNORE_LIMITS =YES
HOME_SEARCH_VEL = -20
HOME_LATCH_VEL = -5
HOME_FINAL_VEL = 7.0
HOME_SEQUENCE = 0
HOME = 0
FERROR = 3.0
MIN_FERROR = 3.0
HOME_OFFSET = 0
HOME_ABSOLUTE_ENCODER	= 2
DIRSETUP   =  6000
DIRHOLD    =  6000
STEPLEN    =  1500
STEPSPACE  =  1500
STEP_SCALE = 1137.7778

```
## This is what I expected to happen:

-  update homing status 

## This is what happened instead:

- Got error Joint xx following error

## It worked properly before this:

- my build file from 27/11/2022 work ok. After pull request from master and rebuild.i got this error.

## Information about my hardware and software:

 * I am using this Linux distribution and version (often, shown by `lsb_release -a`):
 *
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

 * I am using this kernel version (shown by `uname -a`): Linux mwork 4.19.0-23-rt-amd64 #1 SMP PREEMPT RT Debian 4.19.269-1 (2022-12-20) x86_64 GNU/Linux
 
 * I am running ...
   * [ ] A binary I built myself
    
 * I am using this interface hardware vendor and chipset (e.g., parallel port, ethernet port, FPGA card):  7i80db

**Comment by andypugh** [comment]
The most likely culprit is this commit made by me:
https://github.com/LinuxCNC/linuxcnc/commit/f72bd0bd0e31989765df06b9a3478555efe36e40

Can you do a git bisect to prove this? (It shouldn't take very long). 

Instructions here: https://www.metaltoad.com/blog/beginners-guide-git-bisect-process-elimination (obviously you don't need to create a repository with a bad commit)

**Comment by andypugh** [comment]
The fix is probably this change in homing.c
````
        case HOME_FINISHED:
            H[joint_num].homing = 0;
            H[joint_num].homed = 1; // finished
            H[joint_num].home_state = HOME_IDLE;
            if ( ! H[joint_num].home_flags & HOME_ABSOLUTE_ENCODER) {
                joints[joint_num].free_tp.curr_pos = H[joint_num].home;
            }
            immediate_state = 1;
            H[joint_num].joint_in_sequence = 0;
            break;
````
