### ISSUE TITLE
Gmoccapy DRO-size-4axis - doesnt work after restart

### ISSUE THREAD

**Issue by zz912** [LinuxCNC/linuxcnc#2374]
Hello,

in 3 axis Gmoccapy this problem is not.

Simulate problem:
1) run linuxcnc (branche 2.9) 
/configs/sim/gmoccapy/gmoccapy_4_axis.ini
![DRO-size-default_4axis](https://user-images.githubusercontent.com/96618597/222647973-e3cddb0f-cbc8-4b3a-9c42-faec0439127e.png)
2) change DRO - size
![DRO-setting](https://user-images.githubusercontent.com/96618597/222648197-15b55c2d-5d7a-4b75-882f-5b00b9ae3428.png)
3) DRO is correct changed
![DRO-size-changed_4axis](https://user-images.githubusercontent.com/96618597/222648278-106551ef-2118-4eb2-b31e-6d16a9a9a6e8.png)
4) linuxcnc exit
5) run linuxcnc
6) The DRO is not changed, but it should be.
![DRO-size-default_4axis](https://user-images.githubusercontent.com/96618597/222648569-7953391b-a97a-409d-b2de-bc47b2f5b1d2.png)
7) DRO - size value in setting is correct

**Comment by hansu** [comment]
Yeah it seems that the DRO is always displayed smaller than the value from the preferences file.
As a workaround you can set 67 and after restart you have something like 50 ;-)

**Comment by hansu** [comment]
The font size which is actually applied to the DRO elements is reduced if more than 3 DROs are present. But those factors are not taking into account when refreshing the GUI after the setting is changed. So currently it needs a restart to display they correctly.
