### ISSUE TITLE
unexpected move after program stop when remap on_abort_command is used

### ISSUE THREAD

**Issue by propcoder** [LinuxCNC/linuxcnc#241]
Sorry, not enough time to describe everything in detail.

## Here are the steps I follow to reproduce the issue:
Use standard sim config and add remapping or use some remap demo config
add [RS274NGC]ON_ABORT_COMMAND
run some program, stop while running. Watch the surprise move.
TBD

## This is what I expected to happen:
Normal stop.
## This is what happened instead:
unexpected move after program stop

## Information about my hardware and software:
TBD
 * I am using this Linux distribution and version: Debian Wheezy x86
 * I am using this kernel version: TBD
 * I am running LinuxCNC 2.7.8
   * [+] A binary version from linuxcnc.org (including buildbot.linuxcnc.org)

**Comment by alexfloca** [comment]
hi, reported this a couple of years ago, i have just disabled the  ON_ABORT_COMMAND

**Comment by KMevada** [comment]
Even I got the same issue while using ON_ABORT_COMMAND
It seems that vector chained_points  in emccannon is holding some point and not clearing it out. When we call ON_ABORT_COMMAND this generates LINEAR move msg in flush_segments().

Did u find any solution to it?

KAUSHIk
