### ISSUE TITLE
Gmoccapy run from line - button Error

### ISSUE THREAD

**Issue by zz912** [LinuxCNC/linuxcnc#2413]
I tested new version Gmoccapy (branche 2.9) and I found bug with buttons
Tested with:
linuxcnc-2.9_2023-03-15/configs/sim/gmoccapy/gmoccapy.ini

1) Load *.ngc file

2) Cilck Button "Run from line"
![Gmoccapy_run_from_line](https://user-images.githubusercontent.com/96618597/228905509-bebdccf7-d307-425b-8204-c26981ae3ef5.png)

The buttons are crazy.

**Comment by hansu** [comment]
Probably related to https://github.com/LinuxCNC/linuxcnc/pull/2381. @phillc54 can you have a look at this?

**Comment by hansu** [comment]
Okay was a little thing in Gmoccapy related to the conversion of the Calculator's Gtk.Table to a Gtk.Grid.
