### ISSUE TITLE
gremlin - black ghost

### ISSUE THREAD

**Issue by zz912** [LinuxCNC/linuxcnc#2426]
Tested with:
linuxcnc-2.9/configs/sim/gmoccapy/gmoccapy.ini
![black_ghost](https://user-images.githubusercontent.com/96618597/230651080-c08f8f44-abc5-42a1-89f0-b30eed47bf48.png)
I also tested it with gscreen, so the bug is in gremlin, not in Gmoccapy.

**Comment by hansu** [comment]
Also visible in Axis, but not relevant there as the DRO cannot be hidden:

![grafik](https://user-images.githubusercontent.com/67957916/230656362-280b7f01-f5b2-4ff1-a631-544c04220f2d.png)

**Comment by c-morley** [comment]
This is the overlay area.
It is coded in glcanon.py

There is an attribute: show_overlay that can turn it on and off from subclasses.
I would bet it got set to default on in one of the subclasses.

**Comment by hansu** [comment]
Can we add something that the attribute show_overlay will be automatically set to false when no DRO or similar is shown?

**Comment by c-morley** [comment]
You could for sure.
probably right here:
https://github.com/LinuxCNC/linuxcnc/blob/2.9/lib/python/gladevcp/hal_gremlin.py#L179

**Comment by SebKuzminsky** [comment]
Thanks @rene-dev !
