### ISSUE TITLE
gladevcp icon symlinks are rejected by lintian  

### ISSUE THREAD

**Issue by SebKuzminsky** [LinuxCNC/linuxcnc#2440]
GladeVCP installs symlinks for its icons that point to icons that are not part of linuxcnc, but part of libgladeui-common (which is a dependency of linuxcnc).  This violates lintian:
* http://buildbot.linuxcnc.org/buildbot/builders/3304.dsc-buster-rtpreempt/builds/2827/steps/shell/logs/stdio
* http://buildbot2.highlab.com/buildbot/#/builders/6/builds/665/steps/16/logs/stdio

Because lintian fails, we do not publish debs.

I ask that the GladeVCP maintainers (@hansu et al) find and implement a solution for this.  The first thing that comes to mind is to just  usethe libgladeui-common icons directly, instead of creating symlinks to them and using the symlinks, but I defer to your judgement here.

**Comment by hansu** [comment]
>The first thing that comes to mind is to just usethe libgladeui-common icons directly

Yeah, just copying the icons from libgladeui-common to the LinuxCNC repo would have been the easiest solution. But it felt not ideal to have those duplicates in the repo, so I came up with the symlinks. But if lintian does not like them, the only solution I see here is to copy the icons directly.
I'll prepare a PR.

>Because lintian fails, we do not publish debs.

Regarding the debs I wonder about two things: 
- Publishing debs to debian is made manually, right? Because the version in debian unstable was fairly old when I updated the last time
- We are building debs for Bookworm and Bullseye, right? Why don't we have them on http://buildbot.linuxcnc.org/dists/ ?

**Comment by SebKuzminsky** [comment]
> > The first thing that comes to mind is to just usethe libgladeui-common icons directly
> 
> Yeah, just copying the icons from libgladeui-common to the LinuxCNC repo would have been the easiest solution.

I didn't mean copy the icons into our repo, i meant use the icons installed by libgladeui-common.


>     * Publishing debs to debian is made manually, right? Because the version in debian unstable was fairly old when I updated the last time

Yes, the linuxcnc debs on debian.org are manually prepared as dsc (source packages), then uploaded and automatically built into deb (binary packages) by debian's CI infrastructure.  I believe those debs need to be lintian clean to be accepted, especially now that Bookworm is in Freeze. 
 
>     * We are building debs for Bookworm and Bullseye, right? Why don't we have them on http://buildbot.linuxcnc.org/dists/ ?

Because the buildbot is (still!) in transition from the old one (at http://buildbot.linuxcnc.org) that doesn't know how to deal with anything newer than Buster, to the new one (at http://buildbot2.highlab.com) that knows how to deal with all supported distros.

**Comment by hansu** [comment]
>I didn't mean copy the icons into our repo, i meant use the icons installed by libgladeui-common.

As far as I know, the icon names are derived from the widget names. Let me investigate if we can assign different names.

> to the new one (at http://buildbot2.highlab.com/) that knows how to deal with all supported distros.

Great, I didn't know that the debs are available there for download

**Comment by hansu** [comment]
Setting the icon name in the glade catalogue didn't work for all icons. Really weird.
Do you think copying symbolic links would also trigger the linter?

PS: Great to have also Bullseye and Bookworm on https://www.linuxcnc.org/dists/ :+1:

**Comment by hansu** [comment]
@SebKuzminsky can be closed now, right?
