### ISSUE TITLE
QTDRAGON: displays incorrect spindle speed in GUI

### ISSUE THREAD

**Issue by rodw-au** [LinuxCNC/linuxcnc#2447]
## Here are the steps I follow to reproduce the issue:

 1. Converted known good axis config to qtdragon_hd
 2. Checked spindle config was correct by issuing M3 S500 and found
 3.  Speed is displayed incorrectly as wrong pin is used internally in the GUI

## This is what I expected to happen:
Speed would be displayed correctly as it was in Axis

## This is what happened instead:
![spindle error](https://user-images.githubusercontent.com/26877396/233882519-e8db9b36-55cf-411e-89a9-ddf11ba331c5.jpg)
qtdragon insorrectly uses spindle.0.speed-in for spindle speed input, converts it from RPS to RPM and directly updates the GUI field.
This is incorrect. The correct pin to use is spindle.0.speed-out which is correctly scaled to the correct RPM
## Discussion
The image shows the results of  M3 S500. A digital tachometer confirmed the spindle rotates at 500 rpm as confirmed by the value of spindle.0.speed-out. Yet, the display shows 1005 ( spindle.0.speed-in of 16.758 * 60). 
This is not user configurable as qtdragon updates the speed internally. 

Fixing this error should not have any impact on existing configs as a 1:1 spindle drive should show the same RPM for input and output. 

spindle.0.speed-in is the actual motor speed reported by the VFD but if there is a gearbox or belt reduction between the motor and the spindle (as is the case here), the motor speed is not the spindle speed.

## Background (Irrelevant)
 * I am using this Linux distribution and version: Bullseye:
 * I am using this kernel version 5.10
 * I am using this LinuxCNC version (latest 2.9):
 * Hardware, BD600 VFD, with VFDMOD

**Comment by c-morley** [comment]
spindle.0.speed-in should be scaled to actual RPS of the spindle, otherwise spindle sync won't work.

snippet from docs:
spindle.N.speed-in - (float, in) Feedback of actual spindle speed in rotations per second.

spindle.0.speed-out is the requested speed not the actual.
