### ISSUE TITLE
halcompile bug in 2.7 with singleton userspace components

### ISSUE THREAD

**Issue by SebKuzminsky** [LinuxCNC/linuxcnc#245]
User Trần Ngọc Quân posted a singleton userspace comp on the emc-users list: https://sourceforge.net/p/emc/mailman/emc-users/thread/080135e6-4df5-ff80-7c7f-849e9738d966%40gmail.com/#msg35732613

This comp has a few bugs, but also exposes a bug in halcompile: singleton userspace components don't work.  The user_mainloop() function uses the per-instance macros to access the hal pins, but __comp_inst isn't defined.  The docs say to use FOR_ALL_INSTS() in user_mainloop(), but that's silly for a singleton comp.  Maybe singleton comps should define __comp_inst to be __comp_inst_first?

I did my testing in 2.7.

**Comment by vnwildman** [comment]
My comp build and run ok (after some fix) on raspbberypi 3 with machinekit. ![2017-03-19-144540_1824x1024_scrot](https://cloud.githubusercontent.com/assets/508758/24079098/0dcdf5ea-0cb3-11e7-9b66-b5b3cc42f06f.png)

[cpu_thermalusr.txt](https://github.com/LinuxCNC/linuxcnc/files/853073/cpu_thermalusr.txt)

**Comment by jepler** [comment]
@SebKuzminsky  if we take your proposed change, can we still manage to write FOR_EACH_INST in a way that userspace singleton components that used it "unnecessarily" will still work?

**Comment by andypugh** [comment]
This apparently got fixed in Master, but not in 2.7 or 2.8?
https://github.com/LinuxCNC/linuxcnc/commit/2caf046d836cd0d0dbac25cb7e8d2f5c863f1d40#diff-4068db2aca22e5eb7718db692852b257d830760c7e4ed31b371591733070abdf

**Comment by jepler** [comment]
Closing as #664 resolved this in Master.  Release Managers can cherry-pick the fix in #664 back to stable versions if desired.  Thanks!
