### ISSUE TITLE
address of array 'settings->speed_override' will always evaluate to 'true'

### ISSUE THREAD

**Issue by rene-dev** [LinuxCNC/linuxcnc#2483]
when speed_override was changed to an array for multi spindle, use of speed_override in emc/rs274ngc/interp_write.cc has not been updated. clang correctly complains about this.

> emc/rs274ngc/interp_write.cc:165:19: warning: address of array 'settings->speed_override' will always evaluate to 'true' [-Wpointer-bool-conversion]
    if (settings->speed_override) emz[6] =  48;
    ~~  ~~~~~~~~~~^~~~~~~~~~~~~~
emc/rs274ngc/interp_write.cc:167:24: warning: address of array 'settings->speed_override' will always evaluate to 'true' [-Wpointer-bool-conversion]
  } else if (settings->speed_override) {
         ~~  ~~~~~~~~~~^~~~~~~~~~~~~~
emc/rs274ngc/interp_write.cc:318:53: warning: address of array 'settings->speed_override' will always evaluate to 'true' [-Wpointer-bool-conversion]
    state.flags[GM_FLAG_SPEED_OVERRIDE] = settings->speed_override;
                                        ~ ~~~~~~~~~~^~~~~~~~~~~~~~
3 warnings generated.

**Comment by andypugh** [comment]
Addressed (poorly) by b0ad7136e8f046c276b17d1734cc1fc98ee30cd6
