### ISSUE TITLE
halcompile with "option userspace yes" claims to support count= and names= arguments, but does not

### ISSUE THREAD

**Issue by SebKuzminsky** [LinuxCNC/linuxcnc#25]
This is visible in the "jepler/thermistor" branch (31fe16b65d08f6b61f99e3e3067d58e7f53cbd0f).  Inspection of the generated C code shows that no processing of command-line arguments is performed.

**Comment by jepler** [comment]
@SebKuzminsky didn't you fix this in master branch?

**Comment by SebKuzminsky** [comment]
Fixed by commit da3de292f3ffd4a74343f62fe75b0ab1b12d3927 in master.  The old buggy behavior is still in 2.7 and older, it turned out pretty safe-looking so could be backported if needed/wanter.
