### ISSUE TITLE
Error in the documentation

### ISSUE THREAD

**Issue by Sigma1912** [LinuxCNC/linuxcnc#2505]
This example line for a startup code is not valid and causes a config error on startup:
RS274NGC_STARTUP_CODE = G17 G20 G40 G49 G64 P0.001 G80 G90 G92 G94 G97 G98 

http://linuxcnc.org/docs/html/config/ini-config.html#sec:rs274ngc-section
http://linuxcnc.org/docs/devel/html/config/ini-config.html#sub:ini:sec:rs274ngc

The example should, probably, read:
RS274NGC_STARTUP_CODE = G17 G20 G40 G49 G64 P0.001 G80 G90 G92.1 G94 G97 G98

Note the G92.1 instead of G92 which expects axis words

**Comment by Sigma1912** [comment]
Made a Pull Request #2535 regarding this

**Comment by petterreinholdtsen** [comment]
Fixed in 17208cd636dc78c0dbfc9738cfa6558190c8d090 .
