### ISSUE TITLE
Gmoccapy - command.mdi() must be call in mode IDLE only

### ISSUE THREAD

**Issue by zz912** [LinuxCNC/linuxcnc#2524]
This bug may be the cause of this bug:
https://github.com/LinuxCNC/linuxcnc/issues/2453
But I don't want to deal with this connection now.
I would like to fix this bug only to increase the reliability of Gmoccapy.

Here is the definition of the proper use of self.command.mdi() :
http://linuxcnc.org/docs/2.9/html/config/python-interface.html#_preparing_to_send_commands

Here is a call to self.command.mdi("G43) without checking that the mode is IDLE:
https://github.com/LinuxCNC/linuxcnc/blob/56883b969838b721c0b0ebe12b9c14abf91d640e/src/emc/usr_intf/gmoccapy/gmoccapy.py#L3540-L3544
The condition self.stat.task_mode != linuxcnc.MODE_AUTO does not solve the state when the MDI command was started using HALUI.

I could fix it like this:
```
self.stat.poll()
 if "G43" in self.active_gcodes and self.stat.task_mode != linuxcnc.MODE_AUTO and self.stat.interp_state == linuxcnc.INTERP_IDLE: 
     self.command.mode(linuxcnc.MODE_MDI) 
     self.command.wait_complete() 
     self.command.mdi("G43") 
     self.command.wait_complete() 
```
The problem is that I don't know why command G43 is called?
If the condition self.stat.interp_state == linuxcnc.INTERP_IDLE is not met, command G43 will not be executed.
Is it necessary to call command G43 then?

**Comment by gmoccapy** [comment]
Tool handling is redesigned by ReneDev, that should solve this issue. may also be related to #2613
no work on tool handling, as it will be much better in short time
