### ISSUE TITLE
Python Interface: stat.g5x_index returns 0 at startup (should return 1)

### ISSUE THREAD

**Issue by Stutchbury** [LinuxCNC/linuxcnc#2590]
## Here are the steps I follow to reproduce the issue:

 1. Start either the gmoccapy or qtdragon sim
 2. Run the attached Python script `test_g5x_index.py`
 3. Turn the machine 'on'
 4. Optionally 'Home' if you want to select alternate WCS's

## This is what I expected to happen:
The script should report `stat.g5x_index` as the displayed WCS - by default this is G54 so index should be 1.

## This is what happened instead:
The script reports `stat.g5x_index` as 0 (zero) which is not a defined WCS
The index remains at zero unless you change to (eg) G56 and then back to G54. Only then is the index correctly reported as 1. Selecting G54 will not change the index.

For qtdragon this appears to result in the display sometimes showing G59.3 even though it is likely G54 is in operation (as in you have to select a different WCS and then back to G54 to change the display - selecting G54 does nothing) 

## It worked properly before this:
I've not tried this in previous releases.

## Information about my hardware and software:

 * I am using this Linux distribution and version (often, shown by `lsb_release -a`): Debian 12 bookworm
 * I am using this kernel version (shown by `uname -a`): Linux linuxcncdebian12 6.1.0-10-rt-amd64 1 SMP PREEMPT_RT Debian 6.1.37-1 (2023-07-03) x86_64 GNU/Linux
 * I am running ...
   * [X ] A binary version from linuxcnc.org (including buildbot.linuxcnc.org)
 * I am using this LinuxCNC version (shown in package manager or, for git versions, `scripts/get-version-from-git`): LINUXCNC - 2.9.0-pre1-1001-g3b119c4df
 * I am using this user interface (GUI) (e.g., AXIS, Touchy, gmoccapy, etc): gmoccapy and qtdragon
 * I am using this interface hardware vendor and chipset (e.g., parallel port, ethernet port, FPGA card):  Sim
```
import linuxcnc
import time
stat = linuxcnc.stat()

while True:
  stat.poll()
  print("g5x_index: " + format(stat.g5x_index))
  time.sleep(1)
```

[test_g5x_index.py.txt](https://github.com/LinuxCNC/linuxcnc/files/12094569/test_g5x_index.py.txt)

**Comment by c-morley** [comment]
on my system, the latest compiled 2.9 doesn't show this behavior.
Hopefully someone else sees it.

**Comment by Stutchbury** [comment]
Interesting - my sim was created on Sunday and last update from buildbot debs was, I think on Monday (it took me a couple of days to drill down to this as the cause!). I'll do an update tomorrow so I'm on the same version as you and re-create the sim.

**Comment by Stutchbury** [comment]
I am now on version LINUXCNC - 2.9.0-pre1-1011-gebf3cb2c6 which, if understand correctly, is the latest 2.9 from git last night (actually Wednesday night as I've been digging for a while).

On a vanilla gmoccapy or qtdragon this issue no longer appears - unless I load (or have previously loaded) the Manualmatic userspace component - and as before, even if I comment out the manualmatic component, on a restart the issue can (but will not always) appear. 

So there is definitely an 'external influence' here (my apologies for that but the restart bit lead me astray) _however_, the manualmatic component never writes to g5x_index, g92_offset or tool_offset at any time (or g5x_offset at startup, only via MDI if changed). It does _read_ all of the above and this is where it gets interesting - if I place a `time.sleep(0.1)` between reading (technically, setting up a lambda to read) the g5x_index and the g5x_offset then the issue does not occur. To clarify: the issue does not appear the first time starting with the manualmatic component, only after restarting (with or without the component) after having previously started with the component.

I understand this is a particularly esoteric issue and am not looking for support for the manualmatic code (well, not here!) but I am at a loss to explain/understand how/why the issue is caused by a Python Interface 'read', solved by a 'sleep' between two reads and only arises after a restart of LinuxCNC - the test is repeatable and consistent.
 
I'm happy for this issue to be closed but would be happier to find out why it happens as this particular 'gotcha' took a while to track down & work around and wouldn't want anyone else to have to go down that rabbit hole.

If anyone has had their curiosity piqued, inserting a `time.sleep(0.1)` after this line (522 in current commit) 'fixes' the issue:
`self.g5x_index =  MachineStateCommand(Commands.CMD_G5X_INDEX, lambda: self.ls.g5x_index)`
https://github.com/Stutchbury/Manualmatic-Pendant/blob/dev/Software/linuxcnc/python-component/Manualmatic.py#L532

**Comment by c-morley** [comment]
Just a hunch - I  didn't go though all the function calls, but the name of the function is reset - i wonder if in the process of resetting the G5x gets initialized to 0 then set to the user system after. Maybe before that happens, the check for G5x is called. The sleep just takes long enough to allow the G5x to be set properly before reading the G5x state again.

**Comment by Stutchbury** [comment]
A good hunch but the name is possibly a little misleading as it only resets the pendant state (as read from linuxcnc.stat) - this is only called on USB connection or if the task_state (on/off/estop) changes. It may be beneficial to move the lambda creation so it is not recreated on each call to resetState but I think it is only called once for this issue to happen. Should I create a forum thread for further discussion?

**Comment by c-morley** [comment]
Forum might be good - maybe other manualmatics users could get in the discussion.
I'm closing the issue for now.

**Comment by PConn5** [comment]
I’m also seeing this issue on 2.9 (built about two weeks ago from the 2.9.0-pre1 tag). I’m using probe-basic qtpyvcp and don’t use manualmatics. I’ve been seeing this on my machine at startup also where 0 is returned and causes errors in qtpyvcp since it gives index out of range errors not expecting this. I have to switch away from G54 to something else and back to get it to activated.

I see this is closed but looking to figure out what the fix might be because I think this might still be an issue with certain config setups.

Don’t have more info right now but am still digging into it to see if I can find something.

**Comment by PConn5** [comment]
Seemingly related the offsets aren’t loading properly either.

Even if I have saved WCS offsets they are all 0 at startup until I trigger a WCS change or save them again with G10 commands.

When running the same builds in my development sim environment I’m not seeing this issue however.
