### ISSUE TITLE
I am a novice user of LinuxCNC, seeking assistance. This is important for me.

### ISSUE THREAD

**Issue by geekros** [LinuxCNC/linuxcnc#2591]
I am a beginner user of LinuxCNC. Could you please guide me on how to install and set up LinuxCNC in the following system? I hope to receive some instructions to help me get started and learn more effectively.

1、lsb_release -a
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
```

2、uname -a
```
Linux ubuntu 4.14.87 #1 SMP PREEMPT Thu May 25 10:53:03 CST 2023 aarch64 aarch64 aarch64 GNU/Linux
```

Thank you.

**Comment by SebKuzminsky** [comment]
The issue tracker is not a support forum.  Please read the installation documentation here:
<http://linuxcnc.org/docs/2.9/html/getting-started/getting-linuxcnc.html>

If you still have question, ask in the forum here:
<https://forum.linuxcnc.org>
