### ISSUE TITLE
pncconf generates "setp pid.N.maxerror .0005" for all axes in hal for servo configs

### ISSUE THREAD

**Issue by pkmcnc** [LinuxCNC/linuxcnc#26]
2.7.3 and probably earlier versions.
Tested for 5i25 and "7i77x2 with one 7i77", XYZ, mm, default values where possible.
The generated config results in a following error.

**Comment by c-morley** [comment]
confirmed and a fix pushed to 2.7 branch (will come out in next release).
Thanks for the bug report.

Chris M

**Comment by jepler** [comment]
Fixed in commit a14da9b135ee82b8aa1
