### ISSUE TITLE
PNCConf default charge pump frequency is 2500 Hz rather than the intended 10 KHz

### ISSUE THREAD

**Issue by pcw-mesa** [LinuxCNC/linuxcnc#2600]
## Here are the steps I follow to reproduce the issue:

 1. Create a pncconf configuration with a chargepump
 2.
 3.

## This is what I expected to happen:
Although the chargepump frequency is not settable in pncconf, the generated 
hal statements suggest that a 10 KHz chargepump signal has been setup:

---Chargepump StepGen: 0.25 velocity = 10Khz square wave output---

setp   [HMOT](CARD0).stepgen.04.dirsetup        100
setp   [HMOT](CARD0).stepgen.04.dirhold         100
setp   [HMOT](CARD0).stepgen.04.steplen         100
setp   [HMOT](CARD0).stepgen.04.stepspace       100
setp   [HMOT](CARD0).stepgen.04.position-scale  10000
setp   [HMOT](CARD0).stepgen.04.step_type       2
setp   [HMOT](CARD0).stepgen.04.control-type    1
setp   [HMOT](CARD0).stepgen.04.maxaccel        0
setp   [HMOT](CARD0).stepgen.04.maxvel          0
setp   [HMOT](CARD0).stepgen.04.velocity-cmd    0.25

Which makes sense as 10 KHz is what for example a Gecko G540 uses

But these statements in fact generate a 2500 Hz signal

To generate a 10 KHz square wave you would need to set the velocity 
command to 1.0 or perhaps more clearly use a 1.0 scale and a 10000
velocity command:

setp   [HMOT](CARD0).stepgen.04.position-scale  1
setp   [HMOT](CARD0).stepgen.04.velocity-cmd    10000

## Information about my hardware and software:

This is with LinuxCNC master

**Comment by c-morley** [comment]
Thanks Peter - pushed your fix to 2.9/master
