### ISSUE TITLE
AXIS - RIP installation wants outside file

### ISSUE THREAD

**Issue by zz912** [LinuxCNC/linuxcnc#2614]
RIP 2.9 Branche
Debian Bookworm
Oracle VM VirtualBox
Test sim AXIS

I have RIP installation of LinuxCNC. If I wants "Edit tool data..." It wants file from folder, witch is NOT in RIP folder.
 
![Axis-RIP_instalation](https://github.com/LinuxCNC/linuxcnc/assets/96618597/f20178f6-f313-4924-b06d-eed233e1f6a4)

**Comment by d2inventory** [comment]
I can't reproduce the error. Which commit are you using?

git rev-parse HEAD

prints the current active commit hash

**Comment by zz912** [comment]
I dont use git.
I dowloaded linuxcnc-2.9.zip
![image](https://github.com/LinuxCNC/linuxcnc/assets/96618597/14a6980d-ee72-4dda-80ef-af05f5fd879d)

I fixed it for myself:
![image](https://github.com/LinuxCNC/linuxcnc/assets/96618597/efcdeefc-ac15-4dfd-bd63-186d207125eb)

**Comment by d2inventory** [comment]
Where did you get that zip from?

**Comment by zz912** [comment]
![image](https://github.com/LinuxCNC/linuxcnc/assets/96618597/8ac85b68-478d-4eb1-8a53-5f808f2e7319)

**Comment by zz912** [comment]
I dont know, what happened. I cannot reproduce this bug again. I started from clean unzip folder.
Thank you for help.  I apologize for the confusion.

**Comment by zz912** [comment]
Yes, I have icon in desktop for terminal with Rip-environment. I started linuxcnc throw this icon.
