### ISSUE TITLE
pncconf spindle display filter settings dont allow useful filtering

### ISSUE THREAD

**Issue by pcw-mesa** [LinuxCNC/linuxcnc#2618]
The lowpass filter component gain values in pncconf 
are bound to  a minimum 0.5 and maximum of 1.5. 

These are not useful values for display filtering
as a gain of 0.5 translates into a filter 3 db point of about 110 Hz
which is too high to have much effect, and gain values higher 
than 1 are illegal (1 means no filtering at all)
(smaller gain settings result in more filtering)

A better filter gain range would be say .001 to 1
(or specify the filter bandwidth in Hz)

man lowpass

**Comment by c-morley** [comment]
Ok pushed a change to range: 1 to .001
Thank you.
