### ISSUE TITLE
Gmoccapy - DRO digits - do nothing

### ISSUE THREAD

**Issue by zz912** [LinuxCNC/linuxcnc#2625]
RIP 2.9 Branche
Debian Bookworm
Oracle VM VirtualBox
Test sim Gmoccapy.
![DRO-digits-001](https://github.com/LinuxCNC/linuxcnc/assets/96618597/740c5a2e-8018-48b6-a8f1-5cd40a2106a9)
![DRO-digits-002](https://github.com/LinuxCNC/linuxcnc/assets/96618597/3d986faa-0439-4c25-a366-8848039523c2)

**Comment by gmoccapy** [comment]
The bug is caused in combi:dro.py beginning from line 300 in do_set_property.
I will fix that as soon as possible.

Norbert
