### ISSUE TITLE
Axis Sim in Master

### ISSUE THREAD

**Issue by jethornton** [LinuxCNC/linuxcnc#2657]
## Here are the steps I follow to reproduce the issue:

 1. Install Master on Debian 12
 2. Start the Axis Sim

## This is what I expected to happen:
Axis to run

## This is what happened instead:
Note: Using POSIX realtime
./cooling.hal:7: Pin 'iocontrol.0.lube' does not exist
500662
Stopping realtime threads
Unloading hal components

## It worked properly before this:
2.9

**Comment by rene-dev** [comment]
this was fixed in https://github.com/LinuxCNC/linuxcnc/commit/6f82aeed0e8abe296685180c38769b56d37c6e00
