### ISSUE TITLE
rcs_print_debug() has no effect in cms_cfg.cc:cms_create()

### ISSUE THREAD

**Issue by heeplr** [LinuxCNC/linuxcnc#2663]
Some early debug statements like in [cms_create()](https://github.com/LinuxCNC/linuxcnc/blob/master/src/libnml/cms/cms_cfg.cc#L789) never get printed. 

~~It seems as if [the debug flags](https://github.com/LinuxCNC/linuxcnc/blob/master/src/emc/nml_intf/emcargs.cc#L45) are set after cms_create() runs (or maybe as if the flags get reset somewhere between emcGetArgs() and cms_create() and set again before deinit, which might be possible if unlikely).~~

It seems as if [the debug flags](https://github.com/LinuxCNC/linuxcnc/blob/master/src/emc/nml_intf/emcargs.cc#L45) flags are not initialized/inherited by forked children.

Maybe I'll dive into that at some later point. For now leaving this issue for the record.

EDIT: [This set_rcs_print_destination(RCS_PRINT_TO_NULL);](https://github.com/LinuxCNC/linuxcnc/blob/master/src/emc/task/emcsvr.cc#L112) could also play a role.

**Comment by havardAasen** [comment]
@heeplr, did you fix this with #2717?

**Comment by heeplr** [comment]
Yes, forgot to close this. Should be fixed now.
