### ISSUE TITLE
PncConf - area "stepper scale" became black

### ISSUE THREAD

**Issue by zz912** [LinuxCNC/linuxcnc#2670]
I've been getting this error since using version 2.9.

This is a completely random bug. When I turn PncConf off and on, the bug goes away.

Normal state:
![PncConf-area_stepper_scale_is_normal](https://github.com/LinuxCNC/linuxcnc/assets/96618597/0060c76e-6368-4e6e-beef-e7cbc04664e4)

Bug:
![PncConf-area_stepper_scale_became_black](https://github.com/LinuxCNC/linuxcnc/assets/96618597/dafa1eef-6d47-45e7-8642-ba847f43e168)

**Comment by phillc54** [comment]
I don't see that issue on my machines. It may be that it caused by using the deprecated 'override_background'.
Attached is an experimental patch that uses CSS that you may like to try.

[pncconf_css.patch](https://github.com/LinuxCNC/linuxcnc/files/12780472/pncconf_css.patch)

**Comment by zz912** [comment]
> I don't see that issue on my machines.

The bug is random, I couldn't find any dependency.

*.patch file is problem for me. I dont know, how to use it. Could you send me modified files? I will change it in my folders.

**Comment by zz912** [comment]
I tried to make about 10 LCNC configurations and not once did this bug appear.

**Comment by phillc54** [comment]
Is that after the changes?

**Comment by zz912** [comment]
Yes.

**Comment by phillc54** [comment]
Great, thank you. I will wait to see what Chris thinks of the changes.

**Comment by 6XoCtujg2C0gne** [comment]
Folks,
As an FYI, this exact same scenario took place on my machine yesterday.
Regards
Andy

Oct 2, 2023 5:10:45 AM zz912 ***@***.***>:

**Comment by c-morley** [comment]
![pncconf-css](https://github.com/LinuxCNC/linuxcnc/assets/7367477/de910c9b-261b-49c5-8e9a-e8c7c5c43772)
Is this what yours looks like?

Seems to work -just looks odd.

**Comment by zz912** [comment]
I dont have problem with pink button. It worked me with normal red / white button.  I use default xfcee in Bookworm.

**Comment by c-morley** [comment]
It's not the color. It's the fact only the '-' button was colored.

**Comment by phillc54** [comment]
Is it appearing differently on different Linux distributions?
This is on Debian 12:
<img width="892" alt="Screenshot 2023-10-03 at 9 38 21 am" src="https://github.com/LinuxCNC/linuxcnc/assets/2746571/ebc9536a-715c-46f6-8598-5ffd3aad3cef">

**Comment by 6XoCtujg2C0gne** [comment]
I am running Debian 12 also pulled code and compiled.

There is still an issue with the A-Axis. It gets fouled up, cranky and has a fit! Ultimately just melts your screen....

Oct 2, 2023 5:40:26 PM Phillip Carter ***@***.***>:

**Comment by phillc54** [comment]
> There is still an issue with the A-Axis. It gets fouled up, cranky and has a fit! Ultimately just melts your screen....

I am not really sure what you mean by this.
I see no issues on Debian 12 or Debian 11.

**Comment by phillc54** [comment]
I didn't have css set up correctly if both encoders and steppers need changing to red.
This patch fixes that and also names the widgets in the glade files rather than in the python file.
[pncconf_css_1.patch](https://github.com/LinuxCNC/linuxcnc/files/12788119/pncconf_css_1.patch)

**Comment by smoe** [comment]
@phillc54 , could you please prepare a pull request for your patch against 2.9? In principle I could happily do that for you but I likely get the authorships of that patch then wrong.

**Comment by phillc54** [comment]
[done](https://github.com/LinuxCNC/linuxcnc/pull/2798)

**Comment by zz912** [comment]
Can we close this Issue?
