### ISSUE TITLE
RTAI compilation imports flag which enforce C89 for kernel modules. 

### ISSUE THREAD

**Issue by andypugh** [LinuxCNC/linuxcnc#2672]
See https://github.com/LinuxCNC/linuxcnc/commit/3d926d87f14ada9dea313c2989ee8f24f0e54e0c#commitcomment-128575575 for disussion.

**Comment by NTULINUX** [comment]
All of my GNU11 work has been pushed into RTAI master. I also moved the entire musl math library into Kbuild so all the warnings about undefined symbols are also gone. Please do a fresh checkout of RTAI master:

https://github.com/NTULINUX/RTAI/commits/master/
