### ISSUE TITLE
Is this merge correct? - https://github.com/LinuxCNC/linuxcnc/commit/200dfe326832d072db52e3280a29233cd1d82095

### ISSUE THREAD

**Issue by RolandWurst** [LinuxCNC/linuxcnc#2674]
https://github.com/LinuxCNC/linuxcnc/commit/200dfe326832d072db52e3280a29233cd1d82095
![Unbenannt](https://github.com/LinuxCNC/linuxcnc/assets/147000912/0c45510c-f9ee-4afe-8199-98f9e8feccc2)

**Comment by petterreinholdtsen** [comment]
[RolandWurst]
> https://github.com/LinuxCNC/linuxcnc/commit/200dfe326832d072db52e3280a29233cd1d82095
>
![Unbenannt](https://github.com/LinuxCNC/linuxcnc/assets/147000912/0c45510c-f9ee-4afe-8199-98f9e8feccc2)

Hard to tell for an outsider like me.  Why do you ask?

-- 
Happy hacking
Petter Reinholdtsen

**Comment by c-morley** [comment]
That is a copy paste error. Good find!

**Comment by c-morley** [comment]
fixed in 2.9 - thank you.
