### ISSUE TITLE
M code greater than 199:M15816

### ISSUE THREAD

**Issue by TurBoss** [LinuxCNC/linuxcnc#271]
## Here are the steps I follow to reproduce the issue:

 1. Open a very big program > 20 MB
 2. set G54 to any place
 3. run the program and stop it
 4. then open another program 

## This is what happened instead:

a erro is shown in a popup window :
![2017-05-16-165023_1440x900_scrot](https://cloud.githubusercontent.com/assets/184088/26128542/06e13a78-3a8d-11e7-9080-af915b1af96f.png)

## Information about my hardware and software:

linuxcnc latest iso with master rip install from github

Linux cnc28 3.4-9-rtai-686-pae #1 SMP PREEMPT Debian 3.4.55-4linuxcnc i686 GNU/Linux

Thanks

**Comment by SebKuzminsky** [comment]
Please attach the G-code program to this issue.  (Apparently github supports 25 MB attachments: https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/)

**Comment by TurBoss** [comment]
ngc file attached generated with blendercam

[Piedra_Irregular_Muestra.ngc.zip](https://github.com/LinuxCNC/linuxcnc/files/1005936/Piedra_Irregular_Muestra.ngc.zip)

**Comment by TurBoss** [comment]
I'm unable to reproduce this on the simulator x64 but always on the machine x86

pentium 4 2GB ram

**Comment by SebKuzminsky** [comment]
I can reproduce this on the current tip of master (v2.8.0-pre1-3126), but it does not happen on 2.7.8.  I'm testing on a 32-bit x86 VM installed from our 2.6 or 2.7 Live/Install ISO.

On both, the active mcodes as reported by Status, both immediately after aborting the big program and also after trying to load 3D_Chips.ngc are: "M3 M9 M48 M53 M0".

**Comment by jepler** [comment]
I wonder if this is also introduced by the same commit that caused the "G10" problem.  Do we stuff something in the active M codes that is related to file position, and I'm erroneously trying to restore it?

**Comment by jepler** [comment]
Yup.
~~~~
initcodes ['G20', 'g90', 't1 m6', 'g53 g0 X-2.74416465 Y-2.99650464 Z-0.60384252', 'G1.0', 'G17.0', 'G40.0', 'G21.0', 'G90.0', 'G94.0', 'G54.0', 'G43.0', 'G99.0', 'G64.0', 'G97.0', 'G91.1', 'G8.0', 'G43.1 X0.00000000 Y0.00000000 Z0.51100000', 'M3537', 'M3', 'M9', 'M48', 'M53', 'M0']
~~~~

I'll try to get this fixed later in the evening.

**Comment by TurBoss** [comment]
Thank you so much!

**Comment by jepler** [comment]
@TurBoss you're welcome, and thank you for the actionable bug report.  And I'm sorry again for introducing these problems!  They are related to a feature I added that improves preview of "ungrounded" g-code programs, ones that depend on the current machine position and modal codes, rather than establishing them all at the beginning of the part program.

**Comment by jarkko-hautakorpi** [comment]
How should the g code be modified to get rid of the error? Reinstall whole LinuxCNC?
