### ISSUE TITLE
NO_PROBE_JOG_ERROR and NO_PROBE_HOME_ERROR broken

### ISSUE THREAD

**Issue by rene-dev** [LinuxCNC/linuxcnc#2712]
bugreport from IRC:
the feature was added here: https://github.com/LinuxCNC/linuxcnc/commit/90b5d856e98fe64afa6a3ebde350ece60afb60a2
and it broke here: https://github.com/LinuxCNC/linuxcnc/commit/1adc33f11c1f5d317615c824a3e7d16bf060f049

there commits need to be reverted if this ever is added again:
https://github.com/LinuxCNC/linuxcnc/commit/61bdcbf79573cbdf96fb053e95269c4ef06dbf0f
https://github.com/LinuxCNC/linuxcnc/commit/86a69e0b92f7a9858da556f68114683229a232f1

**Comment by mozmck** [comment]
Fix committed in 8bb5e2f
Also reverted those two commits mentioned.

**Comment by mozmck** [comment]
Should this fix be cherry-picked back on 2.9?

**Comment by mozmck** [comment]
Done.
