### ISSUE TITLE
Tools canot be loaded after editting in (at least) qtdragon/Gmoccapy

### ISSUE THREAD

**Issue by c-morley** [LinuxCNC/linuxcnc#2713]
In master branch:
Using a qtdragon sim, after startup, any tool can be loaded. if you edit the tool parameters in qtdragon's builtin tool editor, then you can not load any tool.

you get an error similar to:
emc/task/emctask.cc 68: interp_error: Requested tool 7 not found in the tool table
Requested tool 7 not found in the tool table

Qtdragon handles tool editing by writing directly to the tool file and asking linuxcnc to reload the tool table using python linuxcnc module's load_tool_table(). This is allowed only when linuxcnc is idle

I'm not sure how to debug any further.

**Comment by c-morley** [comment]
Gmoccapy is effected too.

**Comment by rene-dev** [comment]
axis is affected as well. click file->reload after that no tool can be loaded.
