### ISSUE TITLE
Active Gcodes list does not properly reflect applied G52 offsets

### ISSUE THREAD

**Issue by Sigma1912** [LinuxCNC/linuxcnc#2744]
1. Command G52 X100 -> Offset is applied in DRO and active GCodes will show 'G52'
2. Command M2  (or M30)  -> Offset remains applied in DRO but active GCodes no longer shows 'G52'

This is from the documentation:

![G52 caution](https://github.com/LinuxCNC/linuxcnc/assets/46067220/0d9a391c-eeea-492e-99f1-ab9fd83d4f65)

Since the G52/G92 offset remains applied after  M2/M30 then 'G52'/'G92' should not be removed from the active gcodes list.

( related issue for G92: #2743) 

This is using a recent build of version 2.9

**Comment by Sigma1912** [comment]
Looking at this again it seems that the actual issue here is that G52 persists after M2/M30 when it should really be cleared.

**Comment by Sigma1912** [comment]
Seems that G52/G92 handling in LinuxCNC does not follow NISTs RS274NGC standard.
While in the standard the offset  is deactivated on 'm2'/'m30' and the offset values are made 'persistent' by storing them, LinuxCNC will not deactivate G92/G52 offsets on 'm2'/'m30' and both values AND activation state are 'persistent'.
https://tsapps.nist.gov/publication/get_pdf.cfm?pub_id=823374

![RS274NGC_m2](https://github.com/LinuxCNC/linuxcnc/assets/46067220/d9a3de60-4e77-4b2d-b859-048ccc994dbb)  
Looking at the number of tests failing when changing this makes me think that this must have been done intentionally.

**Comment by andypugh** [comment]
Feel free to re-open this if #2935 wasn't actually the fix
