### ISSUE TITLE
Pncconf stepgen spindle doesn't ramp spindle speed

### ISSUE THREAD

**Issue by pcw-mesa** [LinuxCNC/linuxcnc#2748]
When a stepgen driven spindle is setup with pncconf
the stepgen enable pin is connected to spindle on.
 
This cause instant steps in the spindle speed when the spindle
is turned off or a speed of 0 is set.

It would be better to connect the stepgen enable to machine on
allowing use of the stepgen acceleration limits to control the spindle
accel/decel 

 That is replace

net spindle-enable          =>  [HMOT](CARD0).stepgen.0n.enable
 with
net  machine-is-on           =>  [HMOT](CARD0).stepgen.0n.enable

**Comment by c-morley** [comment]
Doesn't  the PID enable pin need to be switched too?

**Comment by pcw-mesa** [comment]
The PID enable  can remain being controlled by spindle enable, 
as it will not cause an instant stop from the stepgen when its velocity 
command output is set to 0.

**Comment by c-morley** [comment]
Thank you. Pushed to 2.9
