### ISSUE TITLE
PncConf - 7i96s_7i74 - missing second port for SSerial

### ISSUE THREAD

**Issue by zz912** [LinuxCNC/linuxcnc#2759]
Configuration for 7i96s+7i74

PncConf generate:
`loadrt hm2_eth board_ip="192.168.1.121" config="num_encoders=1 num_pwmgens=1 num_stepgens=5 sserial_port_0=00000000"`

Should be:
`loadrt hm2_eth board_ip="192.168.1.121" config="num_encoders=1 num_pwmgens=1 num_stepgens=5 sserial_port_0=00000000 sserial_port_1=00000000"`

**Comment by c-morley** [comment]
think this will fix it. #2765

**Comment by zz912** [comment]
I tested it, and your patch fixed it. I tested only PncConf. I did not not tested generated configuration files with physical Mesa cards.

**Comment by c-morley** [comment]
I pushed the fix to 2.9 - thanks.
