### ISSUE TITLE
Mesa digital filters for UART

### ISSUE THREAD

**Issue by sirop** [LinuxCNC/linuxcnc#277]
Hello,

would you accept  such a patch https://github.com/machinekit/machinekit/pull/1212 into linuxcnc?

Any objections?

**Comment by jepler** [comment]
Please file a pull request.  Remember the commits must conform to our signed-off-by policy.

Is there some reason to put this as a flag in the public API, vs just enabling it unconditionally?

**Comment by sirop** [comment]
In rare cases the theoretical bittime might deviate from the real one, for instance, due to temperature dependency of the TTL converter. Then letting the user calculate a deviating FilterReg value  might help.

But I'd rather ask PCW about it.
