### ISSUE TITLE
Typo in Motion.c

### ISSUE THREAD

**Issue by TurboStreetCar** [LinuxCNC/linuxcnc#2773]
Hello, it seems there’s a typo in the names_misc_errors array definitions inside of motion.c. 

It appears it’s using the count of array elements of names_dout instead of names_misc_errors, which effectively prevents you from using the names_misc_errors option. 

Line number 348-351. 

else if(names_misc_errors[0]){
    num_misc_error = count_names(names_dout);
    num_misc_error = (num_misc_error > count_names(names_din)) ? num_misc_error : count_names(names_din);
  }

**Comment by ArchFabricationAndMachine** [comment]
Ive submitted a pull request on this issue.

**Comment by hansu** [comment]
Please link to the corresponding pull request next time: https://github.com/LinuxCNC/linuxcnc/pull/2780

**Comment by andypugh** [comment]
Fixed via https://github.com/LinuxCNC/linuxcnc/commit/74288982e684e03b567d9850efdd105dc209b1f4
