### ISSUE TITLE
Gmoccapy - different number style in tool table

### ISSUE THREAD

**Issue by zz912** [LinuxCNC/linuxcnc#2817]
RIP 2.9 Branche
Debian Bookworm

It is only cosmetic thing. Numbers in tooltable have different style:
![Format_after_touchoff_tool_z](https://github.com/LinuxCNC/linuxcnc/assets/96618597/ae868f27-c6f7-4582-a32a-6e0193b518c9)
![Format_after_apply](https://github.com/LinuxCNC/linuxcnc/assets/96618597/4627ec9c-33ae-4816-bf27-d8abf2cab7b9)

**Comment by hansu** [comment]
That's only when you add a new tool, right?

**Comment by zz912** [comment]
No.

if you use "touchoff tool z" button. I made red elipse in picture.

**Comment by zz912** [comment]
This Issue was solved by https://github.com/LinuxCNC/linuxcnc/pull/3041
