### ISSUE TITLE
PNCconf - Gmoccapy need gmoccapy.tooloffset-x gmoccapy.tooloffset-z

### ISSUE THREAD

**Issue by zz912** [LinuxCNC/linuxcnc#2820]
RIP 2.9 Branche
Debian Bookworm

I would like ask you for adding for Gmoccapy configuration

in main.hal:
```
net tooloffset-x  <=  motion.tooloffset.x
net tooloffset-z  <=  motion.tooloffset.z
```

in gmoccapy_postgui.hal:
```
net tooloffset-x  => gmoccapy.tooloffset-x
net tooloffset-z  => gmoccapy.tooloffset-z
```

This lines controls this:
![tooloffset](https://github.com/LinuxCNC/linuxcnc/assets/96618597/d1fa0c35-d493-4c3a-965a-da7b8044c76d)

I tried modify build_HAL.py , but it was difficult for me. There are many variants.

**Comment by hansu** [comment]
May something like this: https://github.com/LinuxCNC/linuxcnc/pull/2838?

Not tested.

**Comment by zz912** [comment]
PR https://github.com/LinuxCNC/linuxcnc/pull/2838 solved this Issue.
