### ISSUE TITLE
build mesaflash, truetype-tracer packages for stretch (and maybe jessie)

### ISSUE THREAD

**Issue by jepler** [LinuxCNC/linuxcnc#286]
as discussed on IRC, here's the ticket you requested.  thanks in advance.

**Comment by SebKuzminsky** [comment]
and f-engrave, while we're at it

**Comment by SebKuzminsky** [comment]
truetype-tracer debs are now up for Stretch, Jessie, Wheezy, and Precise.

I dropped Lucid, since it's no longer on ftp.ubuntu.com.

**Comment by SebKuzminsky** [comment]
mesaflash master branch doesn't package any more

**Comment by SebKuzminsky** [comment]
add hostmot2 debs for stretch (and jessie?)

**Comment by SebKuzminsky** [comment]
All the debs mentioned in this issue are now on wlo.  Next up: 2.7.10!
