### ISSUE TITLE
Typo regarding "G52", "G92" and DISABLE_G92_PERSISTENCE 

### ISSUE THREAD

**Issue by Unl0gic** [LinuxCNC/linuxcnc#2891]
On the page [linked here](https://linuxcnc.org/docs/html/gcode/overview.html) it says:

- 5210 - 1 if "G52" or "G92" offset is currently applied, 0 otherwise. Volatile by default; persistent if DISABLE_G92_PERSISTENCE = 1 in the [RS274NGC] section of the INI file.

- 5211-5219 - Shared "G52" and "G92" offset for X, Y, Z, A, B, C, U, V & W. Volatile by default; persistent if DISABLE_G92_PERSISTENCE = 1 in the [RS274NGC] section of the INI file.

This seems to have been inverted, shouldn't it say that the parameters in question are persisted by default and volatile only if "DISABLE_G92_PERSISTENCE = 1" is set?

**Comment by andypugh** [comment]
It probably should. 
But do you have the time to check what actually happens? Possibly the INI file entries have confusing names?

**Comment by Sigma1912** [comment]
related https://github.com/LinuxCNC/linuxcnc/pull/2915

**Comment by Sigma1912** [comment]
Oh my, 'DISABLE_G92_PERSISTENCE = 1' is actually broken.
 I had tested with my on_abort command (which also runs on 'machine on') which hid the issue.

I'll have a look.

**Comment by hansu** [comment]
@Unl0gic Is this resolved now?

**Comment by Unl0gic** [comment]
@hansu Yes from what I can see this issue has now been corrected.
