### ISSUE TITLE
Clarify install docs re: sim/uspace

### ISSUE THREAD

**Issue by SebKuzminsky** [LinuxCNC/linuxcnc#29]
Our install docs are not sufficiently clear about how you can run sim/uspace debs on vanilla kernels for simulating your gcode programs, but that's a useful and valuable way to run linuxcnc.

**Comment by jepler** [comment]
we also need to discuss how uspace can be used with rtai and xenomai realtime in master

**Comment by rredford** [comment]
There is rather ugly workaround to get linuxcnc installed on your system. From https://forum.linuxcnc.org/9-installing-linuxcnc/32941-linuxcnc-on-debian-stretch?start=30#96331 :

Error is : Required version of libboost-python is not in stretch repository.

Temporarily point to jessie repo to install such library.

sudo nano /etc/apt/sources.list with nano to contain:
	deb http://ftp.us.debian.org/debian jessie main
sudo apt-get update
sudo apt-get install linuxcnc-uspace

Now remove the pointer to jessie in sources.list
sudo apt-get update

**Comment by rredford** [comment]
Mine is just from repos. I suspect if I build it on system the such workaround isn't needed. We might want to make 2 repo versions, one for linuxcnc system, and one for other linux systems, for sim only.

**Comment by andypugh** [comment]
It's been more than 8 years, but...
