### ISSUE TITLE
pncconf default firmware choice for 7I96S confuses newbees.

### ISSUE THREAD

**Issue by pcw-mesa** [LinuxCNC/linuxcnc#2902]
pncconfs default firmware for the 7I96S is 7I96s_7i74 which creates configurations
that will not run on the standard  pre-installed firmware (7i96s_d) 

7I96s_d should be the default

**Comment by zz912** [comment]
7i96 has the same problem. 7i96d is not first.
![pncconf-default_firmware](https://github.com/LinuxCNC/linuxcnc/assets/96618597/180ecb5b-d17d-45e6-b408-41d8c0565302)

**Comment by pcw-mesa** [comment]
Thank you for fixing this!

**Comment by phillc54** [comment]
Fixed by [PR #2955](https://github.com/LinuxCNC/linuxcnc/pull/2955)
