### ISSUE TITLE
G71 introduces a circle when using the D parameter (remaining distance to stock)

### ISSUE THREAD

**Issue by sundtek** [LinuxCNC/linuxcnc#2939]
In Lathe mode G71 introduces a half circle when using the D parameter, it disappears when not using the D parameter.
I'm using the latest linuxcnc git version (15. March 2024)

G17 G54 G40 G80 G90
G21
G54
G97
G61
g18 g64 g8
G1 F140
S700
M3
G4 P1
G0 Z14.4
#<_startX>=14.3
#<_startZ>=12.5
o100 sub
	G1 X#<_startX> Z#<_startZ>
        G1 X0.01
        G1 Z0 X14.325
        G1 X15
o100 endsub
G71 Q100 X#<_startX> Z#<_startZ> D0.25 I0.2 R1 
M2

that half circle is not correct.

![w0lfzG](https://github.com/LinuxCNC/linuxcnc/assets/6598313/0ffaf967-8223-446b-82f0-15948e8f9c9b)

**Comment by andypugh** [comment]
Is D meant to be a "stock to leave" number? The docs for G71 are terrible, which annoys me as I wrote much better ones for a different implementation of the cycles. 

Does it always fail? Or is is sometimes usable?

**Comment by sundtek** [comment]
I only tested it once and put the result here for the record until someone (or I) have more time to fix it.
D should be stock to leave yes. 
Once the stock to leave is removed it's okay -  the entire circle should not be there when stock to leave is used.

**Comment by andypugh** [comment]
@sundtek Are you able to check if #3020 fixes the issue?

**Comment by sundtek** [comment]
Hi,

I won't be able to test before the end of next month, I was running buster before but the upgrade to bookworm was problematic and introduced some issues with the nvidia graphiccard (those issues are fixed), but LinuxCNC (latest git) refuses to work it wouldn't load motmod.

**Comment by rene-dev** [comment]
Operation not permitted sounds like a permission issue.
also, lxrt? which kernel are you using?

**Comment by sundtek** [comment]
I don't know anymore I just upgraded it in a hurry but did not have time to investigate the last issues... sorry I'm not at the location where this machine is until the end of August (and it's not online either).

**Comment by andypugh** [comment]
I merged the fix into master last night, it should be there now.

**Comment by sundtek** [comment]
ok I will test it tonight.

**Comment by andypugh** [comment]
Fixed?

**Comment by sundtek** [comment]
Sorry it took some time I can confirm that the issue is fixed.
