### ISSUE TITLE
The unit of feed rates are not [mm/m]

### ISSUE THREAD

**Issue by smoe** [LinuxCNC/linuxcnc#2964]
Hello,

I caught a change to the unit of feed rates from [mm/min] to [mm/m] while updating the translations in https://github.com/LinuxCNC/linuxcnc/commit/184084cf4c0b50c0c40c4391df76a00a36ee53f9
committed by @snowgoer540 .

The SI symbol for Minute is indeed "min", see https://en.wikipedia.org/wiki/Minute. Acceptable for me would be [mm/60s] should the minute be frowned upon, but [mm/m] == [1/1000] if picked up by a bad-spirited journalist or decision maker anywhere is bad for the project.

**Comment by snowgoer540** [comment]
Good morning, 

Thank you for the heads up; I pushed a fix for this and will mark this closed. 

I would be remiss if I didn't point out that the Wikipedia article contradicts itself:  "Although not a unit in the International System of Units (SI), the minute is accepted for use in the SI.  The SI symbol for minutes is min (without a dot)."  It should say something like:  "The accepted non-SI symbol for minutes is min (without a dot)."  It would also be helpful if it pointed out that the accepted base SI unit is s for seconds.

Have a good day,
Greg
