### ISSUE TITLE
Posemath #define toLine() is same defined as in Qt library. 

### ISSUE THREAD

**Issue by krcwrhvgyxzqelljes** [LinuxCNC/linuxcnc#2986]
Hi,

~/linuxcnc/src/libnml/posemath/posemath.h
Line 978

The problem is that same name is used in qt libraries.

#define toLine(src,dst) {toPose((src).start, &((dst)->start)); toPose((src).end, &((dst)->end)); toCart((src).uVec, &((dst)->uVec));}

Can you rename this to :

#define toLine_(src,dst) {toPose((src).start, &((dst)->start)); toPose((src).end, &((dst)->end)); toCart((src).uVec, &((dst)->uVec));}

Then it compiles along with qt libraries and problem is solved.

~/qt-creator/5.15.1/gcc_64/include/QtCore/qvariant.h
line 324 :    QLine toLine() const;

Compile ouput:
error: expected ';' at end of declaration list
    QLine toLine() const;

**Comment by rmu75** [comment]
These toLine etc... macros shouldn't be macros in the first place and they should be moved inside the #ifdef __cplusplus block.

**Comment by rmu75** [comment]
These toLine etc... macros shouldn't be macros in the first place and they should be moved inside the #ifdef __cplusplus block.

**Comment by rene-dev** [comment]
closed by https://github.com/LinuxCNC/linuxcnc/pull/2999
