### ISSUE TITLE
Remove StateTag tag. As it is never used.

### ISSUE THREAD

**Issue by krcwrhvgyxzqelljes** [LinuxCNC/linuxcnc#2995]
/home/user/linuxcnc/src/emc/rs274ngc/interp_convert.cc

Line 4357 

StateTag tag;

This can be deleted as it is never used.

**Comment by andypugh** [comment]
In which version? 
In master it is: https://github.com/LinuxCNC/linuxcnc/blob/master/src/emc/rs274ngc/interp_convert.cc#L4357
In 2.9 it is https://github.com/LinuxCNC/linuxcnc/blob/2.9/src/emc/rs274ngc/interp_convert.cc#L4357

**Comment by rmu75** [comment]
https://github.com/LinuxCNC/linuxcnc/blob/2.9/src/emc/rs274ngc/interp_convert.cc#L3811
https://github.com/LinuxCNC/linuxcnc/blob/master/src/emc/rs274ngc/interp_convert.cc#L4352

**Comment by andypugh** [comment]
OK, yes, that seems to never be used in that scope. 
The compiler probably ignores it, but it does seem untidy.

**Comment by rene-dev** [comment]
closed by https://github.com/LinuxCNC/linuxcnc/pull/2999
