### ISSUE TITLE
URL not fining ISO file

### ISSUE THREAD

**Issue by derek084** [LinuxCNC/linuxcnc#2996]

**Comment by andypugh** [comment]
Which URL? Where?

**Comment by derek084** [comment]
Hi Andy,

using this script -

zsync https://www.linuxcnc.org/iso/linuxcnc_2.9.2-amd64.hybrid.iso

Returns

failed on url https://www.linuxcnc.org/iso/linuxcnc_2.9.2-amd64.hybrid.iso
could not read control file from URL
https://www.linuxcnc.org/iso/linuxcnc_2.9.2-amd64.hybrid.iso

Derek



NOTE:
1.  The contents of this email and any attachments are confidential and
privileged.  Any unauthorised use of the contents is expressly prohibited.
If you receive this email in error, please contact the sender and then
delete the email.
2.  Before opening or using any attachments, please check them for viruses
and defects.  The sender does not accept any liability for any damage
caused by such viruses and/or defects.  Please notify the sender of any
virus and/or defect should you discover same.
3.  This email is also subject to copyright.  No part of it should be
reproduced, adapted or communicated without the written consent of the
copyright owner.  Any personal information in this email must be handled in
accordance with the Privacy Act 1988 (Cth).

**Comment by andypugh** [comment]
This looks like a capitalisation difference that was introduced when another developer updated the ISO image. 

zsync https://www.linuxcnc.org/iso/LinuxCNC_2.9.2-amd64.hybrid.iso 

Will probably work.

**Comment by andypugh** [comment]
Sorry, slightly struggling to sort this out properly.

**Comment by derek084** [comment]
All sorted  thanks

**Comment by andypugh** [comment]
I found a secondary problem, it seems to only work with http rather than https. 
Odd, but now fixed I think.
