### ISSUE TITLE
G53 doesn't work right with G92 and coordinate system rotation

### ISSUE THREAD

**Issue by jepler** [LinuxCNC/linuxcnc#30]
Tested in 2.6.11 and master-ish with configs/sim/axis:
1. Start AXIS.  Power on.  Home all.  Clear G54, G92 offsets via menu
2. MDI: G54
3. MDI: G0 G53 X0 Y0
4. MDI: G92 X1 / G10 L2 P1 R45 / G0 G53 X0 Y0

Expected behavior: no motion at step 4, because the machine was already at G53 X0 Y0 after step 3
Actual behavior: motion to machine coordinates (.2929, -.7071)

**Comment by jepler** [comment]
Instead of G0 G53 X0 Y0, you can also G91 G0 X0 Y0, which should cause motion since it's in incremental distance mode with all distances zero.  It takes you to the same machine location as the G0 G53 version.
![rotation-g92-wrongmotion](https://cloud.githubusercontent.com/assets/1517291/12522349/c18dfc1e-c115-11e5-9506-8cf8d0f61440.png)

**Comment by jepler** [comment]
Thanks!  The best way to get a change accepted into linuxcnc is by preparing a pull request. Patches added to issues are likely to get lost.

**Comment by andypugh** [comment]
Seems to be fixed by #1297
