### ISSUE TITLE
COMPONENT PIN NAMES ARE GETTING TOO LONG

### ISSUE THREAD

**Issue by bennyb1** [LinuxCNC/linuxcnc#3037]
## Problem with long  names 
 Some components have long pin or component names or both.
 
<img width="396" alt="MOTION FUNCTION BLOCK" src="https://github.com/user-attachments/assets/bcdce969-0fdd-48f6-bc66-fe322274bb45">

## This is what I expected to happen:
Programmers should refrain from using long names.
Developers should try to follow IEC 1131 standard for names.

## This is what happened instead:
I use an schematic capture software to draw hal based schematics, then run a custom script to convert the schematic into a hal file.
Long names makes the component function blocks large which consumes valubale cad sheets space.

## Information about my hardware and software:
I am using Autodesk Eagle for schematic caputure and a built in customized script to generate hal file.

**Comment by jethornton** [comment]
What does IEC 1131 have to do with this project? IEC 1131 is for PLC languages.

The basic principle of IEC-1131 is that a programmer can develop a control algorithm (referred to as a "Project") using any combination of five control languages; Instruction List, Structured Text, Ladder Diagram, Function Block Diagram, and Sequential Function Chart.

**Comment by rmu75** [comment]
YOU CAN IMPLEMENT THAT A MAPPING BETWEEN SHORT AND LONG PIN NAMES IN YOUR SCRIPT THAT GENERATES THE HAL FILE. E.G. USE "FIPS" IN YOUR SCHEMATIC AND HAVE THE SCRIPT TRANSLATE "FIPS" TO "FEED-INCHES-PER-MINUTE" IN YOUR HAL FILE.

**Comment by bennyb1** [comment]
Thank you Robert for your suggestion to map pins to keep component names and pin names short. 

Regards,

Ben Benissa
