### ISSUE TITLE
master branch. Luck of probe_material_z function / versa_probe

### ISSUE THREAD

**Issue by chernogorsky** [LinuxCNC/linuxcnc#3068]
## Here are the steps I follow to reproduce the issue:

 1. Enable versa_probe
 2. Go to probe tab
 3. Select check block Z height

## This is what I expected to happen:
It starts working

## This is what happened instead:
It has an error "function probe_material_z not in probe routine"

## It worked properly before this:
it works in 2.9.3

and it has that function in 
probe_routines.py

When def probe_material_z(self): copied from 2.9.3 and inserted into /usr/lib/python3/dist-packages/qtvcp/widgets/probe_routines.py
it works as expected

## Information about my hardware and software:
 * I am running ...
   * [X] A binary I built myself (from git master branch)

**Comment by c-morley** [comment]
Looks like it was accidental with last push - I'll fix it soon. Sorry

**Comment by c-morley** [comment]
Should be fixed now.
