### ISSUE TITLE
Wrong link in documentation

### ISSUE THREAD

**Issue by gmoccapy** [LinuxCNC/linuxcnc#310]
in
/src/hal/drivers/mesa-hostmot2/doc/README.regmap

the link:
https://github.com/linuxcnc/hostmot2-firmware/blob/master/regmap

leads to Error 404

IMHO it should be

https://github.com/linuxcnc/hostmot2-firmware/

If I am right, I will change that link.

Norbert

**Comment by SebKuzminsky** [comment]
The link is wrong in different ways in 2.7 and master.  Since we ship hostmot2 bitfiles from the "v0" branch, I think our docs (in both branches) should point here:

https://github.com/LinuxCNC/hostmot2-firmware/blob/v0/regmap

**Comment by gmoccapy** [comment]
corrected the links in 2.7 and master and pushed the changes.

Norbert
