### ISSUE TITLE
ini doc has incorrect value for increments

### ISSUE THREAD

**Issue by jethornton** [LinuxCNC/linuxcnc#3100]
2.9 ini-config.adoc

INCREMENTS = 1 mm, .5 in, …​ - Defines the increments available for incremental jogs. The INCREMENTS can be used to override the default. The values can be decimal numbers (e.g., 0.1000) or fractional numbers (e.g., 1/16), optionally followed by a unit (cm, mm, um, inch, in or mil). If a unit is not specified the machine unit is assumed. Metric and imperial distances may be mixed: INCREMENTS = 1 inch, 1 mil, 1 cm, 1 mm, 1 µm is a valid entry.

µm is not a valid unit only um is tested for in Axis.

https://github.com/LinuxCNC/linuxcnc/blob/master/src/emc/usr_intf/axis/scripts/axis.py#L1470****

2.8 and older docs have the correct unit of um

**Comment by hansu** [comment]
Fixed with adfc62f7715b9782ff4f06bca7041c4a16f7efdc
