### ISSUE TITLE
linuxcnc reports "Unable to open file <>" on any gcode error

### ISSUE THREAD

**Issue by rene-dev** [LinuxCNC/linuxcnc#311]
## Here are the steps I follow to reproduce the issue:

open sim/axis
load gcode file with error

## This is what I expected to happen:

get a detailed report of the error

## This is what happened instead:

Unable to open file <>

## It worked properly before this:

still present in 2.7.10, not in 2.7.9
https://github.com/LinuxCNC/linuxcnc/compare/v2.7.9...v2.7.10

## Information about my hardware and software:
A binary I built myself v2.8.0-pre1-3277-g063b79b3d

**Comment by jepler** [comment]
See #308 and the fix #309.
