### ISSUE TITLE
axis: DRO disappears when attempting "Show machine position"

### ISSUE THREAD

**Issue by ReeseWang** [LinuxCNC/linuxcnc#328]
## Here are the steps I follow to reproduce the issue:

 1. The key is that I have A axis with WRAPPED_ROTARY = 1
 2. Start LinuxCNC using this ini: https://github.com/ReeseWang/syil-x5-linuxcnc-config/blob/1736b038d408f510bd32057ba05e21b86566f05e/Syil_X5/Syil_X5_restart.ini
 3. Home all. All axes should home immediately without triggering switches.
 4. Stay on Preview tab.
 5. Press "#" or select "Show machine position" from menus.

## This is what I expected to happen:

DRO on the top left of preview back plot shows current machine coordinate.

## This is what happened instead:

DRO texts disappeared in the preview back plot.

Python threw following exception:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1437, in __call__
    return self.func(*args)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 498, in callit
    func(*args)
  File "/usr/bin/axis", line 512, in actual_tkRedraw
    self.tkRedraw_perspective()
  File "/usr/bin/axis", line 472, in tkRedraw_perspective
    self.redraw_perspective()
  File "/usr/lib/pymodules/python2.7/rs274/glcanon.py", line 314, in inner
    return f(self, *args, **kw)
  File "/usr/lib/pymodules/python2.7/rs274/glcanon.py", line 513, in redraw_perspective
    self.redraw()
  File "/usr/bin/axis", line 550, in redraw
    GlCanonDraw.redraw(self)
  File "/usr/lib/pymodules/python2.7/rs274/glcanon.py", line 1171, in redraw
    limit, homed, posstrs, droposstrs = self.posstrs()
  File "/usr/lib/pymodules/python2.7/rs274/glcanon.py", line 1291, in posstrs
    positions[3] = math.fmod(positions[3], 360.0)
TypeError: 'tuple' object does not support item assignment
```

## It worked properly before this:
(If the behavior changed after making a particular change in hardware or
software, describe the change you think is responsible.  E.g., "after upgrading
from LinuxCNC 2.7.3 to 2.7.4")

## Information about my hardware and software:

 * I am using this Linux distribution and version (often, shown by `lsb_release -a`): Debian Wheezy, shipped with LinuxCNC live CD.
 * I am using this kernel version (shown by `uname -a`): 3.4-9-rtai-686-pae #1 SMP PREEMPT Debian 3.4.55-4linuxcnc i686 GNU/Linux
 * I am running ...
   * [x] A binary version from linuxcnc.org (including buildbot.linuxcnc.org)
   * [ ] A binary I built myself
   * [ ] A binary version from some other source besides linuxcnc.org
 * I am using this LinuxCNC version (shown in package manager or, for git versions, `scripts/get-version-from-git`): 2.7.11
 * I am using this user interface (GUI) (e.g., AXIS, Touchy, gmoccapy, etc): AXIS
 * I am using this interface hardware vendor and chipset (e.g., parallel port, ethernet port, FPGA card): Parallel port

**Comment by jepler** [comment]
We believe this is fixed by #370
