### ISSUE TITLE
dependencies for MINT 18.2 are not reported corect

### ISSUE THREAD

**Issue by gmoccapy** [LinuxCNC/linuxcnc#334]
On current master and:
MINT 18.2 'Sonja'
Cinnamon 64-bit
with Kernel:
4.10.0-28-generic

I did:
```
cd
sudo apt-get install git git-gui
git clone https://github.com/LinuxCNC/linuxcnc.git linuxcnc-dev
sudo apt-get update
cd /linuxcnc-dev/debian
./configure uspace

cd ..
dpkg-checkbuilddeps
```
and installed the mentioned dependencies with:
```
sudo apt-get install build-essential debhelper libudev-dev libxenomai-dev tcl8.6-dev tk8.6-dev libreadline-gplv2-dev asciidoc dblatex  dvipng graphviz groff inkscape source-highlight texlive-font-utils texlive-lang-cyrillic texlive-lang-french texlive-lang-german texlive-lang-polish texlive-lang-spanish w3c-linkchecker python-tk libxmu-dev libglu1-mesa-dev libgl1-mesa-dev libboost-python-dev libmodbus-dev libusb-1.0-0-dev
```
went on with:
```
cd src
./autogen.sh
./configure --enable-simulator
```
and got missing dependencies of:
bwidget 
libtk-img 
tclx

after finishing with make and sudo make setuid and rip-environment I was not able to start hal_gremlin based GUI's as python-gtkglext1 was also missing.

I am not sure, where to add that dependencies or even if I am allowed to.
Any help appreciated.

Norbert

**Comment by jepler** [comment]
You are confusing the build dependencies of LinuxCNC with the runtime dependencies of LinuxCNC.  There are some dependencies that are required only at runtime, not when building the package.  `dpkg-checkbuilddeps` (and related programs such as `mk-build-deps`) only install build-time dependencies.  We can't change this, it's a part of how Debian works.

I see we do mention `dpkg-checkbuilddeps` in the documentation, please feel free to offer pull requests that improve the documentation.
