### ISSUE TITLE
Apparent bug by inspection in mesa-hostmot2/encoder.c:hm2_encoder_read_control_register

### ISSUE THREAD

**Issue by jepler** [LinuxCNC/linuxcnc#343]
The code is attempting to track the prior value of `quad-error-enable`.  However, it does this by a single static value `last_error_enable`.  It looks like if not all encoders have the same `quad-error-enable` value, it won't work properly, possibly leading to errors occurring and not being reported.

In particular, imagine a setup with 2 channels. channel 0 has `quad-error-enable TRUE` and channel 1 has `quad-error-enable FALSE`.  Each time channel 0 is handled in the `for`-loop, last_error_enable will be 0 because it was set the previous cycle when channel 1 was handled.

**Comment by andypugh** [comment]
Fixed by 2334748708de6bacfac3fa284aafec9289906154
