### ISSUE TITLE
Linuxcnc on i.MX6 board

### ISSUE THREAD

**Issue by Savoyyang** [LinuxCNC/linuxcnc#352]
hey , I know LinuxCNC(Machinekit) can transplant to BeagleBoneBlack(Debian)和Raspberry Pi3(Debian)，Now I want to transplant on i.MX6 board，but can't find more information on internet. I know this is possible, but there is no more information, can you provide some information, thank you very much.

**Comment by jepler** [comment]
This is a place for reporting bugs in the software, not requesting help compiling or using it.  Please consider using https://forum.linuxcnc.org/ in the future.

I don't have any experience with the specific ARM board you mention, but the workflow is the same: Build LinuxCNC from source on the target board (or build a debian package on some other system with a compatible architecture and install it).

All ARM boards are incompatible as far as I/O is concerned, so you have to write your own hardware interface code as a HAL component.  We welcome pull requests for such components, as long as the contributors are also going to maintain them.
