### ISSUE TITLE
limit3 constraint violation

### ISSUE THREAD

**Issue by SebKuzminsky** [LinuxCNC/linuxcnc#378]
We've discovered two glitches in @zultron's new limit3 component.  A new test added in 3eb0a7a1b247aa34bb80549c7b045b56ba1007c6 reproduces both.

The first glitch is when limit3's input abruptly begins to track its output.  This bug was fixed in a0fb2781268ac1c5eec049bf7ea6b4fa2ebf84c3.

The second glitch is an accel constraint violation that seems related to hunting for a constant-velocity input.
![limit3-accel-violation](https://user-images.githubusercontent.com/400548/33853168-3f6b1eae-de7a-11e7-8967-a6caf9b144df.png)

**Comment by zultron** [comment]
Refs to #351, #240.  Thanks, @SebKuzminsky.  I'll take a look.

One of these may have been fixed over the weekend by @dngarrett and @samcoinc (and maybe others).

**Comment by zultron** [comment]
I have a fix for this, and will clean up and submit PR by tomorrow.

The fix is trivial; just a case of being sloppy with values persisting between calls.

**Comment by zultron** [comment]
I've gone off in the weeds a bit on this one, but I'll submit a PR by tomorrow for real.  :P 

In addition to the present fix, I also fixed the math a bit, and the overshoot problem is greatly reduced.

**Comment by zultron** [comment]
So much for submitting a PR "by tomorrow for real", 29 days later.  My apologies.

PR #396 should fix these issues.

**Comment by samcoinc** [comment]
Can't rush into these things.  :) The violation is certainly gone - initial testing looks awesome!.
