### ISSUE TITLE
PID html documentation out of date

### ISSUE THREAD

**Issue by pcw-mesa** [LinuxCNC/linuxcnc#388]
# The issue tracker is not a support forum

The LinuxCNC issue tracker is to report bugs in the software.
If you have a question about how to use the software, use one of the other methods detailed on our community support page: http://linuxcnc.org/community/

(delete this section before submitting your bug report)

## Here are the steps I follow to reproduce the issue:

 1. View http://linuxcnc.org/docs/2.7/html/hal/rtcomps.html#_pid
 2. man PID
 3.

## This is what I expected to happen:
They should be the same
## This is what happened instead:
The HTML shows the PID tuning numbers as parameters, they are actually pins now

## It worked properly before this:
(If the behavior changed after making a particular change in hardware or
software, describe the change you think is responsible.  E.g., "after upgrading
from LinuxCNC 2.7.3 to 2.7.4")
Not sure when this changed (PID tuning setting changed to pins) but its been quite a while...
## Information about my hardware and software:

 * I am using this Linux distribution and version (often, shown by `lsb_release -a`):
 * I am using this kernel version (shown by `uname -a`):
 * I am running ...
   * [ ] A binary version from linuxcnc.org (including buildbot.linuxcnc.org)
   * [ ] A binary I built myself
   * [ ] A binary version from some other source besides linuxcnc.org
 * I am using this LinuxCNC version (shown in package manager or, for git versions, `scripts/get-version-from-git`):
 * I am using this user interface (GUI) (e.g., AXIS, Touchy, gmoccapy, etc):
 * I am using this interface hardware vendor and chipset (e.g., parallel port, ethernet port, FPGA card):

**Comment by andypugh** [comment]
Fixed, I think.
