### ISSUE TITLE
puma560 sim error

### ISSUE THREAD

**Issue by lethang12cdt** [LinuxCNC/linuxcnc#390]
Whenever i control robot Puma560 via MDI mode (Manual mode is ok), the terminal will show : "ERR kI - compute_jinv (joints: 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000), (iterations=0) " but the linuxcnc is still running.

## Here are the steps I follow to reproduce the issue:

 1. Open linuxcnc by command line
 2. Run the puma560 in sim/axis/vismach/puma/puma560
 3. Home all --> select MDI mode --> command Gcode

**Comment by andypugh** [comment]
Merge with https://github.com/LinuxCNC/linuxcnc/issues/384
