### ISSUE TITLE
Joint Value Jump ON_ABORT_COMMAND

### ISSUE THREAD

**Issue by KaushikM19** [LinuxCNC/linuxcnc#393]
Hello all,
Whenever I use ON_ABORT_COMMAND in RS274NGC section, joints motor-pos-cmd value run away on abort.

Linuxcnc: Master 

Configuration file:
[axis_mm.TXT](https://github.com/LinuxCNC/linuxcnc/files/1608690/axis_mm.TXT)

GCode:
[GCODE_FILE.TXT](https://github.com/LinuxCNC/linuxcnc/files/1608692/GCODE_FILE.TXT)

Kaushik

**Comment by petterreinholdtsen** [comment]
Might be related to #241.
