### ISSUE TITLE
PnCConf Backlash will not set 'STEPGEN_MAXVEL' and 'STEPGEN_MAXACCEL'

### ISSUE THREAD

**Issue by larrykvit** [LinuxCNC/linuxcnc#395]
## Here are the steps I follow to reproduce the issue:

 1. Use PnCConf to configure ini and hal file
 2. Turn on the back lash compensation
 3. 'STEPGEN_MAXVEL' and 'STEPGEN_MAXACCEL' properties are not set in the ini files

## This is what I expected to happen:
'STEPGEN_MAXVEL' and 'STEPGEN_MAXACCEL' properties should be set

## This is what happened instead:
'STEPGEN_MAXVEL' and 'STEPGEN_MAXACCEL' properties are not set. They are referenced in the hal file, thus linuxcnc does not start

## It worked properly before this:
Without backlash compensation it works properly.
It only affects the axis for which back lash compensation is turned on.

## Information about my hardware and software:
Latest linuxcnc (2.7.11), using a mesa 7i76e
Looks like this bug has been around for at least a year:
https://forum.linuxcnc.org/39-pncconf/31749-pncconf-and-backlash

**Comment by c-morley** [comment]
Thank you for the report.
I have fixed this in 2.7 and master.
It will come out in the next bug fix release.
Or you can get it very soon from the buldbot.
