### ISSUE TITLE
mesa_7i65 comp causes kernel panic

### ISSUE THREAD

**Issue by pcw-mesa** [LinuxCNC/linuxcnc#451]
## Here are the steps I follow to reproduce the issue:

Run Linuxcnc with the halfile/hardware for mesa_7i65 component

## This is what I expected to happen:
Run normally

## This is what happened instead:
Causes a kernel panic about 1/3 time you launch or leave LinuxCNC
Driver seems to work properly if it launches OK

## It worked properly before this:
Not sure 2.8 also reportedly has this issue

## Information about my hardware and software:

LinucCNC 2.7.12 or LinuxCNC 2.7.14

  
  2.7.12 binary version is from linuxcnc.org
  2.7.14 binary version is built from source locally
 Hardware is 5I20 card + 7I65

**Comment by andypugh** [comment]
Both PCW and myself think that patch works. I recommend pushing to 2.7. Or even 2.6 :-)
