### ISSUE TITLE
O code Document

### ISSUE THREAD

**Issue by jethornton** [LinuxCNC/linuxcnc#453]
In the O Codes chapter is this statement correct?
The behavior is undefined if: Comments are used on a line with an O-word 

I've tested in 2.7 adding comments after the O-word with no errors.

o100 sub (test)
	(msg, o100 test)
o100 endsub (end test)

o100 call (call test)

M2

**Comment by andypugh** [comment]
On 30 June 2018 at 15:26, jethornton <notifications@github.com> wrote:

> That question in that link seems to say "undefined because different
> compliers do different things in C++". It seems to me with only one parser
> that it either works or does not work.
>

To be pedantic, there are at least two parsers, and the infrastructure
allows for more.

-- 
atp

**Comment by jepler** [comment]
```
READ => G0 X0 (hi)
    6 N..... COMMENT("hi")
    7 N..... STRAIGHT_TRAVERSE(0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000)
READ => G0 (hi) X0
    8 N..... COMMENT("hi")
    9 N..... STRAIGHT_TRAVERSE(0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000)
READ => O100 (hi) if
Unknown control command in o word
O100 (hi) if
```
Comments in O-word lines do not work in the same way as comments in other places.

Another way to look at a statement that such and such is undefined behavior is that the developers want to retain wiggle room here and make future changes.

**Comment by jethornton** [comment]
The documents have been updated to to inform users not to put comments on the same line as the O word and the examples corrected
