### ISSUE TITLE
Editing an O-word sub while lInuxCNC is live gives a spurious "Duplicate O-word error"

### ISSUE THREAD

**Issue by andypugh** [LinuxCNC/linuxcnc#455]
Discussion and details here:
https://forum.linuxcnc.org/20-g-code/27728-duplicate-o-word-label-error-in-version-2-6?limitstart=0#113181

**Comment by KurtJacobson** [comment]
I can confirm this on the latest master. It only happens on the first call to the sub after editing, subsequent calls behave as expected.

**Comment by andypugh** [comment]
Do we think this is a big enough problem to leave as an open issue? 
Maybe we just document the behaviour?

**Comment by zultron** [comment]
Heh, I hadn't seen this one.

This does indeed have to do with caching; see the `offset_map` in `src/emc/rs274ngc`.  I'm submitting a PR for it in #555.

**Comment by manymachines** [comment]
I verified this fix with the current 2.8 branch (I'm the guy from the forum discussion).  I think this issue can be closed now?  Thanks!

**Comment by andypugh** [comment]
Thanks
