### ISSUE TITLE
PID component does not use command-deriv pin if connected

### ISSUE THREAD

**Issue by pcw-mesa** [LinuxCNC/linuxcnc#466]
## Here are the steps I follow to reproduce the issue:

 1. Run LinuxCNC with pid.n.command-deriv connected to a signal
 2. check that the PID uses the command-deriv value
 3.

## This is what I expected to happen:
use the command-deriv pin if that pin is connected

## This is what happened instead:
It always uses d/dt of pid.n.command

## It worked properly before this:
Just tested master but probably 2.7 and even 2.6 are affected

## Information about my hardware and software:
master/uspace/Ethernet

**Comment by andypugh** [comment]
That seems to suggest that the dummysig trick does not actually work? 
https://sourceforge.net/p/emc/mailman/message/26519176/

**Comment by jepler** [comment]
Can you say a little more about your testing procedure?  I set up the following:
```
loadrt threads 
loadrt pid num_chan=2 debug=1
loadrt siggen
addf siggen.0.update thread1
addf pid.0.do-pid-calcs thread1
addf pid.1.do-pid-calcs thread1
net cmd siggen.0.sine pid.0.command pid.1.command
net cmdderiv siggen.0.triangle pid.0.command-deriv
start
```

and scoped `pid.[01].errorD`.  One looks like a triangle, and the other looks like a sine.  This makes me believe the command-deriv functionality is working.
![image](https://user-images.githubusercontent.com/1517291/42882957-cc3464da-8a5f-11e8-99f3-626ab138c480.png)

**Comment by pcw-mesa** [comment]
This is where this started: https://forum.linuxcnc.org/10-advanced-configuration/34827-joint-vel-cmd-for-torque-pid-loop-and-linear-encoder-pid?start=10

**Comment by jepler** [comment]
OK, then does this image capture the problem?  Similar to before, except now I am additionally scoping 'commandD'.  In the case of pid.0 with the command-deriv pin connected, the errorD pin reflects the command-deriv value but the commandD pin does not.

![image](https://user-images.githubusercontent.com/1517291/42911454-9df7bbb6-8ab0-11e8-8143-0f8599a060e3.png)

**Comment by jepler** [comment]
and would the following screenshot represent corrected behavior?
![image](https://user-images.githubusercontent.com/1517291/42911567-2667ca90-8ab1-11e8-935d-5c8fbf7941c4.png)

**Comment by pcw-mesa** [comment]
Not sure about the debug pins, where I saw a problem is  with just FF1=1 the pid.n.command-deriv pin value does not change the pid output

**Comment by mozmck** [comment]
Closing this because the merge says it closes this issue - I don't know why github didn't auto-close it.
