### ISSUE TITLE
There are a GRBL Connection Board?

### ISSUE THREAD

**Issue by se3d** [LinuxCNC/linuxcnc#469]
Looking for a option to CNC on linux , was not possible to use this version with my board (Arduino + cnc child). Now, I'm working with laserweb4 , but raspberry pi 3 is running without native tools , only a remote access by server of laser web. 

There are a way to use the linux cnc with grbl compatible boards?

**Comment by pcw-mesa** [comment]
LinuxCNC is a motion controller like GRBL, that is, it is an alternative machine controller to GRBL. 
It will not run on the same hardware as GRBL.
It needs as a minimum Linux compatible hardware and a Linux installation.
If LinuxCNC controls hardware, it also needs a real time Linux kernel.

**Comment by rene-dev** [comment]
GRBL is buffered motion. The timing model of linuxcnc does not work with buffered motion.
http://wiki.linuxcnc.org/cgi-bin/wiki.pl?HardwareDesign
