### ISSUE TITLE
spindle-at-speed not working with multi spindle

### ISSUE THREAD

**Issue by rene-dev** [LinuxCNC/linuxcnc#504]
1. load sim/axis, home.
2. halcmd unlinkp spindle.0.at-speed
3. halcmd setp spindle.0.at-speed 0
4. run the program, wait for it to wait for the spindle to start
5. halcmd setp spindle.0.at-speed 1
6. it should continue, but doesn't. It behaved correctly before multi spindle.

**Comment by andypugh** [comment]
Fixed
eb8d43f
