### ISSUE TITLE
Jessie ISO

### ISSUE THREAD

**Issue by JonnyTech** [LinuxCNC/linuxcnc#51]
Are there any plans to release - or is there a test version somewhere - of the LinuxCNC ISO with Jessie rather than Wheezy?

**Comment by SebKuzminsky** [comment]
We currently don't have a reliable realtime kernel for Jessie.  After someone makes one we'll release a Jessie install ISO.

There was an attempt at an RTAI kernel for Jessie but it was flaky on the buildbot and the problems were never fully debugged:

http://linuxcnc.org/2015/11/29/new-rtai-kernel/
http://linuxcnc.org/2015/12/30/RTAI-5-support-merged/

**Comment by JonnyTech** [comment]
Thanks for the quick reply - I will consider trying the test builds if I am feeling adventurous.
