### ISSUE TITLE
pncconf error with units in fields

### ISSUE THREAD

**Issue by TurBoss** [LinuxCNC/linuxcnc#514]
I'm having issues with unit fields in pncconf

scale set to 160000 instead of 160 when click accept/ok in axis calculator
and travel area multiplied by 10 when click on "back" button

## Information about my hardware and software:

 * I am using this Linuxcnc stretch iso:
 * I am running ...
   * [X] A binary version from linuxcnc.org buildbot.linuxcnc.org

> hazzy:
TurBoss: I was able to reproduce the pncconf problem. It occurs when a comma is used as the decimal seperator
It appears that the comma is ignored, so 120,0 is converted to the number 1200
TurBoss
hazzy: but I didn't put any dot or comma
it does automatically
hazzy
Yes, GTK puts it in automaticaly because of your local
That also explains why your STEP_SCALE was 1000 times what it should be the other day. The calculator adds three decimal places, and GTK correctly used a comma for the decimal seperator because of your local, but PNCConf interpreted that as 160000 instead of 160

Thanks

**Comment by TurBoss** [comment]
linux 4.9.0-8-rt-amd64
LINUXCNC - 2.8.0-pre1-3928-g0cab36566

**Comment by c-morley** [comment]
What local are you using?

**Comment by TurBoss** [comment]
my system language?
spanish

**Comment by c-morley** [comment]
Thanks, I'l try to look into it soon.

**Comment by TurBoss** [comment]
Hello, 

any news about this?
Thanks

**Comment by c-morley** [comment]
Sorry I got busy...I have confirmed the error.
A work around would be to run pncconf in an English locale.
running from terminal like this:
LANG=C pncconf

**Comment by c-morley** [comment]
Ok I pushed a fix for this to master.
Let me know if this cures the problem for you.

**Comment by TurBoss** [comment]
no updates on buildbot

**Comment by SebKuzminsky** [comment]
There was a spurious build failure on the master branch, which prevented the buildbot from producing packages with this fix.  I just kicked off the build again, hopefully it'll pass and the debs should be ready in a few hours.

**Comment by TurBoss** [comment]
fixed now shows 125,0000

Thanks
closing this
