### ISSUE TITLE
Gcode spiral

### ISSUE THREAD

**Issue by JonnyTech** [LinuxCNC/linuxcnc#52]
This is more of a gcode question than an issue, but can someone please help?

Looking at the spiral example: https://github.com/LinuxCNC/linuxcnc/blob/master/nc_files/spiral.ngc

1:
g91 g1 @-.0025 ^4.5
What do the @ and ^ symbols mean?

2:
The example starts from outside working in.
How do I start from center working outwards?

Any pointers would be very helpful - many thanks.

**Comment by jepler** [comment]
http://linuxcnc.org/docs/2.7/html/gcode/overview.html#_polar_coordinates
