### ISSUE TITLE
Gmoccapy error with overrides after merge from 2.7

### ISSUE THREAD

**Issue by c-morley** [LinuxCNC/linuxcnc#529]
Discussed a bit at:
https://forum.linuxcnc.org/9-installing-linuxcnc/35532-rolling-back-to-2-7-from-2-8

looks like last merge (e3ydca) from 2.7 mixed the code as 2.7 Gmoccapy uses max-velocity but master uses rapid-override.

probably best that Norbert looks at the code.

**Comment by rene-dev** [comment]
I think I messed up the merge: https://github.com/LinuxCNC/linuxcnc/commit/e37dca40ef29a087caf338ff157913bcfef0fd6c#diff-80f0ace7d76deff21d3c7b9f696b8ef0R2514
@gmoccapy said he has a look.

**Comment by gmoccapy** [comment]
I just pushed a fix for this issue, it should be fixed.
Thanks for reporting the bug.

Norbert
