### ISSUE TITLE
reorganize isos on www.linuxcnc.org website

### ISSUE THREAD

**Issue by SebKuzminsky** [LinuxCNC/linuxcnc#53]
Old isos are in /iso, new isos are in /.
Probably move the new ones to /iso and place symlinks in / pointing at the real locations.

**Comment by MarcWeber** [comment]
It's even more important to talk on the Download page that there are old i686 isos in the /isos folder.
Took me quite long to find out. We want to resurrect an old printer requiring parallelport hence the need for very old hardware.

A simple sentence (amd64 isos: ...) and a simple link __older isos also i686 32 bit can be found at isos/__ would be enough. Should one minute to improve the website.
