### ISSUE TITLE
Add to Readme purpose and type of this software

### ISSUE THREAD

**Issue by matkoniecz** [LinuxCNC/linuxcnc#539]
I would be happy to make a PR if that would be desirable (let me know if that is the case). For start 

> LinuxCNC controls CNC machines. It can drive milling machines, lathes, 3d printers, laser cutters, plasma cutters, robot arms, hexapods, and more. http://linuxcnc.org/

may be a good initial readme content (currently it has solely disclaimer and link to build instruction).

**Comment by matkoniecz** [comment]
And for the type of software I am still trying to confirm what it is.

- text on http://linuxcnc.org/ makes clear that it is a software
- http://linuxcnc.org/docs/2.7/html/getting-started/getting-linuxcnc.html - distributed as live CD so it is either separate OS or software hard enough to install that it is distributed as live CD or maybe software directed toward people with Windows and unwilling to install linux.
- further installation instructions suggest that it is actually impossible to install as normal software and requires separate OS (`Reboot, and select the Linux 3.2.0-4-rt-686-pae kernel. `)

**Comment by andypugh** [comment]
LinuxCNC is a software  application that is dependent on a specific type of non-standard Linux kernel to work. (ie one with real-time extensions, PREEMPT-RT, RTAI or Xenomai) 
The kernel patches do not interfere with the other OS functions in any way, so the Linux install appears normal.

**Comment by matkoniecz** [comment]
And it is a monolithic application, so it is impossible to install just parts that do not require special kernel features?

Or it possible to install just some tools?

**Comment by andypugh** [comment]
No, it is made up of many parts, and these can be used independently in a modular way. 
But it doesn't really do anything useful without the realtime capability.

**Comment by matkoniecz** [comment]
So it impossible to generate gcode with http://linuxcnc.org/docs/2.4/html/gui_image-to-gcode.html export it and use it on machine that operates CNC cutter?

Is it limitation of LinuxCNC or is my understanding of gcode as instructions executed by a CNC machine incorrect?

**Comment by rmu75** [comment]
Usually, a linuxcnc system is a fully functional linux system.  You can install and run whatever linux stuff you like.

As andypugh said, operating a real machine requires the use of a non-standard kernel that has certain realtime-capabilities, but those capabilities do not interfere with other OS functions in any way.

Software that requires proprietary kernel modules may be a problem, but this stuff is to be avoided anyways.

**Comment by andypugh** [comment]
I no longer believe that I understand the context of this discussion. 
Is this a pull-request for changes to the LinuxCNC docs?

To answer the most recent question: Yes, of course you can run image-to-gcode without LinuxCNC, you can run it on any system with a Python interpreter, it is just a standalone script:
https://github.com/LinuxCNC/linuxcnc/blob/master/src/emc/usr_intf/axis/scripts/image-to-gcode.py
Or do it online: https://www.thuijzer.nl/image2gcode/

But why install LinuxCNC to do that? LinuxCNC is intended to be the controller for the CNC cutter that you mentioned, and image-to-gcode is just a convenience filter (possibly even only an example to illustrate the use of filters)

**Comment by matkoniecz** [comment]
> I no longer believe that I understand the context of this discussion.

Sorry, that is probably result of that I am a bit confused and not explaining myself clearly.

>  Is this a pull-request for changes to the LinuxCNC docs?

No, pull request is at https://github.com/LinuxCNC/linuxcnc/pull/540

> To answer the most recent question: Yes, of course you can run image-to-gcode without LinuxCNC, you can run it on any system with a Python interpreter, it is just a standalone script:

I was completely unaware about this, thanks! (though from reading http://linuxcnc.org/docs/2.4/html/gui_image-to-gcode.html again I see no way to learn that from the documentation, maybe this also may be worth doing)

Thanks!
