### ISSUE TITLE
Documentation error re O-word subs

### ISSUE THREAD

**Issue by andypugh** [LinuxCNC/linuxcnc#564]
See https://forum.linuxcnc.org/32-documents/36121-clarification-of-subroutine-return-data#127424

The documentation section 3 states that O-word subroutines can not return values
Then section 9 describes how values are returned. 

http://linuxcnc.org/docs/html/gcode/o-code.html#ocode:subroutines

**Comment by jethornton** [comment]
I fixed 2.7 Documentation just need someone that knows how to merge it to master.

**Comment by jethornton** [comment]
fixed in master as well
