### ISSUE TITLE
halcmd alias command deletes original pin/parameter

### ISSUE THREAD

**Issue by pcw-mesa** [LinuxCNC/linuxcnc#567]
Halcmds alias function deletes the original pin/parameter 
contrary to the man page for halcmd. 

This is true on LinuxCNC 2.7 and 2.8

To test
halcmd alias pin motion.adaptive-feed maf
halcmd show pin | grep adaptive 
 (motion.adaptive-feed is gone)

**Comment by andypugh** [comment]
Curious. Do you think that this needs a fix to the docs, or should both pins exist?

**Comment by pcw-mesa** [comment]
My opinion is that because that function is called "alias" it should not remove the original name
wonder what the author thinks...
(also removing names leads to some pretty weird situations where say signals are netted to pins
in the hal file that disappear... I suspect this is OK since I guess names just resolve to pointers but still weird...)

**Comment by andypugh** [comment]
I tested part of that, if you alias a pin it remains in the same net with the new name.

**Comment by andypugh** [comment]
This might just be an issue with "show pin". You can still use the original name in a net command. 
(and "show pin" shows the alias netted to the new signal)

**Comment by pcw-mesa** [comment]
OK thanks for testing that, I guess this makes some kind sense of sense as a listing of 
pin --> signals connections would be a bit confusing with multiple names I think I will close this
with a note that this behavior could be better documented.

**Comment by andypugh** [comment]
8841b630976745a8c38a3b2318762c1c1e3fb783
