### ISSUE TITLE
Stepconf forces addition of mdi commands

### ISSUE THREAD

**Issue by jethornton** [LinuxCNC/linuxcnc#574]
When you select adding the halui hal user interface pins you're forced to add a MDI_COMMAND to the [HALUI] section. This is not correct at all. Adding the halui user interface pins have nothing to do with adding MDI commands in the poorly named [HALUI]  section.

**Comment by c-morley** [comment]
Are you saying that Stepconf adds MDI commands to the INI which are not needed or that HALUI should look elsewhere for it's MDI commands?

**Comment by c-morley** [comment]
Oh ok looks like there is a HALUI MDI command page that requires you to add a command.
I agree you should be able to go past the page without entering an MDI command.

**Comment by c-morley** [comment]
fixed with 5ea93f8
