### ISSUE TITLE
Stepconf uses minimum step times at least for G540 causing failure to work with 3.3V parallel ports

### ISSUE THREAD

**Issue by pcw-mesa** [LinuxCNC/linuxcnc#577]
## Here are the steps I follow to reproduce the issue:

 1. Run stepconf
 2. select G540 parameters
 3. G540 absolute minimum step time is used

Suggest all timing be double the drives specifications which are almost always minimums

G540 is especially bad because it specifies 1 usec minimum step time 
but needs closer to 2.5 usec with 3.3V parallel ports

## This is what I expected to happen:
Some timing margins 
## This is what happened instead:
0 timing margins

## Information about my hardware and software:
 LinuxCNC master (but probably every version)

**Comment by c-morley** [comment]
This has been changed in stepconf and pncconf to 5000,5000,10000,10000
I have not changed any other driver timing - maybe we should.
