### ISSUE TITLE
Add a manpage for the hal_parport component

### ISSUE THREAD

**Issue by SebKuzminsky** [LinuxCNC/linuxcnc#58]
We have asciidocs for the component here: http://linuxcnc.org/docs/2.7/html/hal/parallel-port.html

But it's convenient to have a manpage too, so we should add that.

There's currently a hal_parport manpage in section 3hal, describing the old API for accessing a parallel port from code in a component (used by ppmc, 7i43, 7i90, and pluto).

**Comment by cradek** [comment]
Thank you @WJHildreth for this addition in 2.7
