### ISSUE TITLE
INI parameter access in G-Code

### ISSUE THREAD

**Issue by Eranziel** [LinuxCNC/linuxcnc#582]
## Here are the steps I follow to reproduce the issue:

 1. Create a .ngc file which reads an INI file parameter using `#<_ini[section]name>`.
 2. Try to run the file.

Here's a simple example:
```
#<xhome> = #<_ini[axis_x]min_limit>
g0 #<xhome>

M2
```

## This is what I expected to happen:
`#<_ini[axis_x]min_limit>` should return the value from the INI file. In this case, 0.0.

## This is what happened instead:
Interpreter gives the following error:
```
G-Code error in temp.ngc
Near line 2 of
/home/user/linuxcnc/nc_files/temp.ngc
Named parameter #<_ini[axis_x]min_limit> not defined
```

This functionality is mentioned in the [devel docs](http://linuxcnc.org/docs/devel/html/remap/remap.html#remap:referto-inifile-variables). The note at the bottom of the section implies it was part of a branch - either the functionality should be merged into master (my personal preference), or the documentation removed.

**Comment by andypugh** [comment]
Have you enabled the feature using the FEATURE_MASK described in section 18?

http://linuxcnc.org/docs/devel/html/remap/remap.html#_optional_interpreter_features_ini_file_configuration

**Comment by zultron** [comment]
The confusing comment @Eranziel refers to is also in the [2.7 documentation][1]:

> Caution | this section doesn’t really belong here but since it comes with the same branch, here it rests for now until its clear this will be merged. It should go into the gcode/overview Named Parameters section.

It looks like something that wasn't caught during review.

It would make good sense to explicitly note this is an experimental feature and add a pointer to section 18 for how to enable it.

[1]: http://linuxcnc.org/docs/2.7/html/remap/remap.html#remap:referto-inifile-variables

**Comment by andypugh** [comment]
I can also see little reason for it not to default to “on” 
I am more wary of doing that with HAL pin values.

**Comment by sebastiankuzminsky** [comment]
FWIW, I agree with @andypugh .  As far as possible, let's try to have a single set of features, always on.

**Comment by SebKuzminsky** [comment]
FWIW I agree with @andypugh.  As far as possible let's try to have a single set of features, always on.

**Comment by Eranziel** [comment]
Well, I completely missed that when I read section 18, my mistake.

However, I've now added `FEATURES = 8` to the RS274NGC section and I get the same result. Can anyone else confirm?

FWIW, my personal preference would be to default that feature to ON as well. I may or may not be biased by currently working on a project where I want to use it...

**Comment by andypugh** [comment]
It's 4 to turn on INI parameter access, and 4 to turn on HAL pin access. 
(or 12 to make sure and turn on both)

**Comment by Eranziel** [comment]
Total reading comprehension fail there, my bad. It does work when you turn it on. ;)

Shall I close this, or leave it open until the documentation gets adjusted?

**Comment by andypugh** [comment]
Leave it open, as we seem to have decided to change something.

**Comment by gmoccapy** [comment]
I agree with Andy, FEATURES = 12 should be the default value.

Norbert

**Comment by phillc54** [comment]
FEATURES = 12 as the default makes sense to me

**Comment by mozmck** [comment]
I vote for FEATURES = 12 as the default as well.  I've been using that for a long time for both INI settings and HAL pins without any problems.

**Comment by andypugh** [comment]
We don't use "FEATURES" at all any more.
 74fc4491014b9de4141c44f58e391960e681343b
