### ISSUE TITLE
make it easier to change realtime's rtapi_app's msg_level

### ISSUE THREAD

**Issue by SebKuzminsky** [LinuxCNC/linuxcnc#59]
Currently (as of 2.7.4) the only way to change rtapi's logging message level is to change the source code and recompile.  It would be better if it was easier, perhaps through the [EMC]DEBUG setting in the ini file or similar.

**Comment by SebKuzminsky** [comment]
RTAI's realtime logging is controlled through /proc, which is also awkward.

It would be good if we could control all rtapi implementations' msg_level in some consistent way, perhaps by a new NML message to Motion, or new Motion HAL pins.

**Comment by jepler** [comment]
.. and that /proc code is disabled for kernels 3.10 and greater too

**Comment by jmkasunich** [comment]
Regarding Seb's suggestion that rtapi's message level be controlled by an NML message to motion, or by motion HAL pins - please consider that some people use HAL without motion.  A halcmd command to change the debug level would be more appropriate.  Also, it is theoretically possible to use RTAPI for things other than HAL.  (Although I doubt anyone does.)  So even using halcmd to set the level wouldn't satisfy a purist...  I'm not that much of a purist, but I don't think that a method involving the motion component is appropriate.

**Comment by andypugh** [comment]
Can you elaborate on the disablement of /proc ? Is that a kernel thing or a LinuxCNC thing?
I have got used to echoing a number to somewhere in /proc to change the reporting level.

**Comment by jepler** [comment]
In the distant past, RTAPI + RTAI created entries in /proc.  By kernel 3.10, the APIs for doing so changed incompatibly, and nobody updated the code to continue working -- I just disabled it instead.   (ec38ac4566e07baa3e47e0a0463ac7384c92f3aa).  But creating /proc entries is simply not possible for uspace-style realtime, so it's not a good solution for that either.

**Comment by andypugh** [comment]
I think that I fixed this, without closing the issue, in 2020 via 07dcd21
