### ISSUE TITLE
missleading German translation

### ISSUE THREAD

**Issue by DaveBrauns** [LinuxCNC/linuxcnc#597]
I am using the official Wheezy 2.7 iso image with the axis gui.
The translation for resetting the coordinate systems is a little bit missleading, it only says "Koordinatensystem" instead of "Koordinatensystem zuruecksetzen" or "Koordinatensystem null setzen"
Because of this wrong or incomplete translation I messed up my G54 Offset, I thougth I would select it and not clear it.

**Comment by andypugh** [comment]
I think you can edit this directly on github, see the pencil icon at the top of the text frame:
Was it this one here? https://github.com/LinuxCNC/linuxcnc/blob/2.7/src/po/de.po#L5382

**Comment by rene-dev** [comment]
thanks!
