### ISSUE TITLE
Unit tests for C++ sources (interp / task / canon)

### ISSUE THREAD

**Issue by robEllenberg** [LinuxCNC/linuxcnc#618]

**Comment by andypugh** [comment]
I am sure that these are a good idea. Do you need anything from the rest of us?

**Comment by mozmck** [comment]
I think he wants us to review PR #619 :-)  I just set my review to approved, but it wouldn't hurt if you could look at it.

**Comment by robEllenberg** [comment]
@mozmck exactly, it would be nice to have more eyes on it as a sanity check.

**Comment by andypugh** [comment]
I can barely read C++ :-) 
Plain C and Python (and, irrelevantly) VBA are the ones that I can just read and understand.

**Comment by mozmck** [comment]
@robEllenberg; can we close this issue now that the PR was merged?

**Comment by robEllenberg** [comment]
Yes, I have some additional tests to merge in the future, but everything we need to write tests is in place now.
