### ISSUE TITLE
hal_glib.py error in Gmoccapy

### ISSUE THREAD

**Issue by phillc54** [LinuxCNC/linuxcnc#622]
After updating a master branch RIP build the following error appears when starting Gmoccapy:

Traceback (most recent call last):
  File "/home/phill/git/linuxcnc-dev/lib/python/hal_glib.py", line 406, in update
    tool_num_new = self.old['tool-prep-number']
KeyError: 'tool-prep-number'

The Axis GUI works perfectly.

It worked before the update.

**Comment by c-morley** [comment]
sorry... fixed

Chris M

________________________________

**Comment by phillc54** [comment]
Thanks Chris, that was quick, and it works a treat.
