### ISSUE TITLE
When homing single axis after failed homing, more than one axis is homed

### ISSUE THREAD

**Issue by grandixximo** [LinuxCNC/linuxcnc#650]
## Here are the steps I follow to reproduce the issue:

 1.Open linuxcnc with axis_9axis configuration
 2.Home and stop immediatly after by pressing ESC while Z is still homing
 3.select Z axis and press home button on keyboard to home single axis

## This is what I expected to happen:

Only Z axis home procedure is executed

## This is what happened instead:

All 9 axis home procedure is executed

## It worked properly before this:
This issue is not present on 2.7.14, but it is present on 2.8 and 2.9

## Information about my hardware and software:

 * I am using this Linux distribution and version (often, shown by `lsb_release -a`): Ubuntu 18.04.3 LTS
 * I am running ...
   * [ ] A binary version from linuxcnc.org (including buildbot.linuxcnc.org)
   * [x] A binary I built myself from latest git
   * [ ] A binary version from some other source besides linuxcnc.org
 * I am using this LinuxCNC version (shown in package manager or, for git versions, `scripts/get-version-from-git`): linuxcnc-uspace_2.9.0~pre0_amd64
 * I am using this user interface (GUI) (e.g., AXIS, Touchy, gmoccapy, etc): AXIS

**Comment by grandixximo** [comment]
I'd like to propose a fix

in the homing.c file, near the end of the file in the case HOME_ABORT need to add 

`joint_in_sequence[joint_num]=0;`

I think this is the correct fix

**Comment by dngarrett** [comment]
Verified -- thanks for the report, the method to replicate using a sim config, and the proposed fix.  Bug exists in the 2.8 branch too, will fix

**Comment by grandixximo** [comment]
You are welcome :-)
