### ISSUE TITLE
Debian package contains wrong dependency

### ISSUE THREAD

**Issue by zwieblum** [LinuxCNC/linuxcnc#684]
debian/configure contains 2 wrong entries to python-gst0.10 and streamer0.10-plugins-base (all other refernces to these packages have already been changed to python-gst-1.0 and gstreamer1.0-plugins-base). 

Way to resolve:

sed 's#python-gst0.10#python-gst-1.0#g' -i debian/configure
sed 's#gstreamer0.10-plugins-base#gstreamer1.0-plugins-base#g' -i debian/configure

**Comment by luzpaz** [comment]
@zwieblum is this still the case or can this ticket be closed ?

**Comment by zwieblum** [comment]
Can be closed, there's no python2 any more.
