### ISSUE TITLE
Part of classicladder file format marked for translation

### ISSUE THREAD

**Issue by jepler** [LinuxCNC/linuxcnc#717]
@andypugh noticed that some items marked for translation are actually lines that must be written to / read from classicladder files.  These cannot depend on language, otherwise a French user cannot use a ladder file she received from a Russian user.  https://github.com/LinuxCNC/linuxcnc/blob/822db89fa9ef3e0ef974b040782eab43378daba8/src/hal/classicladder/manager_gtk.c#L119

**Comment by andypugh** [comment]
Fixed via 3c7abae2d38de8616699235bcd54051076c5c8e2
