### ISSUE TITLE
Removed Arc OK High was useful

### ISSUE THREAD

**Issue by KimPrzy** [LinuxCNC/linuxcnc#721]
Removed Arc OK High feature supported immediate detection of arc loss (open circuit) by plasmac - long before (if at all) detection/response by welfare/import and/or transformer based plasma power supplies.

**Comment by phillc54** [comment]
I can restore it but it will need to be able to be set to a very high voltage to account for HF start machines. I will discuss this with Tom on the forum.

**Comment by phillc54** [comment]
I have reinstated Arc OK High. It now has a ridiculously high default of 99999 so hopefully that will cover all bases.
