### ISSUE TITLE
GMOCCAPY handling of A (or other angular) axis does not implement default settings

### ISSUE THREAD

**Issue by GuiHue** [LinuxCNC/linuxcnc#722]
Not so much a bug, but a missing piece of implementation in gmoccapy.
Regardless of the values for DEFAULT_ANGULAR_VELOCITY (tried 36, 180, 360, ...) gmoccapy starts with a velocity of 360°/min and goes up to 10 times that (3600°/min). I had expected the value in the gui to change according to the ini file.

linuxcnc.org/docs/devel/html/gui/gmoccapy.html doe snot mention "angular" at all.  Reviewing the code shows, that src/emc/usr_intf/gmoccapy/getiniinfo.py does not read the information and src/emc/usr_intf/gmoccapy/gmoccapy.py does not make use of the information. Over all angular information handling seems to be minimal.

## Here are the steps I follow to reproduce the issue:
1. Setup gmoccapy for XYZA configuration in machine.ini, enter
2. Enter information regarding default_angular_velocity as follows
3. Start linuxcnc and notice that default settings are being ignored:)
Settings examples:
[DISPLAY]
DEFAULT_ANGULAR_VELOCITY = 36
MAX_ANGULAR_VELOCITY = 36
MIN_ANGULAR_VELOCITY = 0

[TRAJ]
COORDINATES =  X Y Z A
LINEAR_UNITS = mm
ANGULAR_UNITS = degree
DEFAULT_LINEAR_VELOCITY = 166.667
MAX_LINEAR_VELOCITY = 166.667
DEFAULT_ANGULAR_VELOCITY = 36
MAX_ANGULAR_VELOCITY = 36

See also:
https://forum.linuxcnc.org/gmoccapy/38811-gmoccapy-v3-handling-of-angular-velocity#163618

## This is what I expected to happen:
Have gmoccapy behave the same way for linear information as it does for angular settings.

## This is what happened instead:
see above; constant values are used

## It worked properly before this:
Does not apply, missing feature

## Information about my hardware and software:
* Debian 9 Stretch in recent kernel
* LinuxCNC Master via Buildbot

**Comment by gmoccapy** [comment]
Fixed with b7c8bb3 on 11.08.2020 19:47
gmoccapy now takes care of DISPLAY entries of 
MIN_ANGULAR_VELOCITY
DEFAULT_ANGULAR_VELOCITY
MAX_ANGULAR_VELOCITY
