### ISSUE TITLE
qtdragon: error when deleting the error log

### ISSUE THREAD

**Issue by seebaer1976** [LinuxCNC/linuxcnc#734]
sorry for my english

have an error message with qtdragon when deleting the alarm log.

here is the message:

> error:
> Qtvcp encountered an error.  The following information may be useful in troubleshooting:
> LinuxCNC Version  : 2.8.0-pre1-5649-gec411a428
>  
> QTvcp ERROR! Message # 2
>  
> 

> by clicking on show details:
> >  
> > Traceback (most recent call last):
> > File "/usr/share/qtvcp/screens/qtdragon/qtdragon_handler.py", line 367, in btn_clear_alarms_clicked
> > ACTION.UPDATE_MACHINE_LOG('update-machine-log', None, 'DELETE')
> > TypeError: UPDATE_MACHINE_LOG() takes at most 3 arguments (4 given)
> >  

maybe someone has a solution

mfg
seebaer1976

**Comment by c-morley** [comment]
yes this has been fixed recently but here is how if you don't want to update for some reason.
(change line 367 in the handler file):

        ACTION.UPDATE_MACHINE_LOG('', 'DELETE')

**Comment by seebaer1976** [comment]
thanks
