### ISSUE TITLE
halmodule.0 test fails with python3

### ISSUE THREAD

**Issue by rene-dev** [LinuxCNC/linuxcnc#818]
line 50 and 58 fail:
https://github.com/LinuxCNC/linuxcnc/blob/master/tests/halmodule.0/test.py#L50-L58
the problem is probably here:
https://github.com/LinuxCNC/linuxcnc/blob/master/src/hal/halmodule.cc#L66-L80

**Comment by dwrobel** [comment]
Hopefully should be addressed by https://github.com/LinuxCNC/linuxcnc/pull/824.

**Comment by rene-dev** [comment]
fixed, thanks!
