### ISSUE TITLE
Stepconf broken in master with python2

### ISSUE THREAD

**Issue by c-morley** [LinuxCNC/linuxcnc#840]
build_ini.py has on line 38:
importlib.reload(sys)

Which seems is python3 only

In stepconf.py line 53 there is:
reload(sys)

Would that be python2 only?

changing the build-ini.py to reload(sys) fixes things in python2

I'm actually not not sure of the python version policy for master are we supporting both or transitioning to python3 only?

**Comment by rene-dev** [comment]
Oh, looks like I missed that bit. I will take care of it.

**Comment by rene-dev** [comment]
I think the idea is to drop 2 once everything works, but Im not sure.

**Comment by rene-dev** [comment]
Should be fixed, please test.
I think stepconf should be 2 and 3 compatible, as it is generally used by users, not developers (so stepconf bugs will be fixed in 2.8), and they use 2.8, not master. we should merge the changes into 2.8, so 2.8 and master have the same codebase.

**Comment by c-morley** [comment]
Yes it's fixed now -thanks.
probably unrelated but when I compile I see this:

gcc: fatal error: no input files
compilation terminated.
expr: syntax error

but it still compiles fine.

**Comment by rene-dev** [comment]
thats probably unrelated. please repoen if there is a problem with stepconf on python3.

**Comment by dwrobel** [comment]
>Should be fixed, please test.

@rene-dev I found some more issues which should be fixed now by https://github.com/LinuxCNC/linuxcnc/pull/848.

>gcc: fatal error: no input files
>compilation terminated.
>expr: syntax error

@c-morley Could you please share the full output of the following:
 - `$ gcc -dumpversion && echo OK || echo NOK`
 - `$ gcc -dumpfullversion && echo OK || echo NOK`
