### ISSUE TITLE
HTML Docs master branch do not contain image URLS

### ISSUE THREAD

**Issue by rodw-au** [LinuxCNC/linuxcnc#860]
## Here are the steps I follow to reproduce the issue:

 1. Go to Master branch docs : http://linuxcnc.org/docs/devel/html/
 2. Open a link that contains images (eg homing configuration)

## This is what I expected to happen:
Images in the document should be displayed

## This is what happened instead:
Images  are not displayed becasue no image URL is included in the HTML source eg.
<img src="" alt="Example Homing Switch layout" />
`<img src="" alt="Example Homing Switch layout" />`
This issue affects a number of documents I reviewed so I think it is a global issue

## It worked properly before this:
2.8 branch HTML is correctly formatted and images are displayed

**Comment by phillc54** [comment]
That seems like it may be a Buildbot issue, the documents appear to build OK locally.

**Comment by phillc54** [comment]
Looks like a missing module on the Buildbot, all images seem to bring up this error.

http://buildbot.linuxcnc.org/buildbot/builders/2000.docs/builds/5554/steps/compile/logs/warnings%20%283630%29

**Comment by plasmac-linuxcnc** [comment]
fixed by #901
