### ISSUE TITLE
halmeter and halscope still using gtk2

### ISSUE THREAD

**Issue by rene-dev** [LinuxCNC/linuxcnc#864]
they are written in c, and should be ported to gtk3.
pncconf and this are the last parts that depend on legacy gtk versions.

**Comment by havardAasen** [comment]
I've done some work on this. not complete but I'm not sure if I can swap out `CList` without breaking anything. It still works with gtk2 and can be implemented in this master branch.

Isn't classicladder still using some outdated gtk functions?

**Comment by rene-dev** [comment]
yes, classicladder also uses gtk2. breakign stuff isnt an issue.
can you create a PR to my gtk3 branch? https://github.com/LinuxCNC/linuxcnc/pull/943
