### ISSUE TITLE
/usr/bin/update_ini: ImportError: No module named tkinter

### ISSUE THREAD

**Issue by arvidbrodin** [LinuxCNC/linuxcnc#881]
On a clean Debian buster installation with linuxcnc-2.9.0~pre0 installed according to [these](https://forum.linuxcnc.org/9-installing-linuxcnc/38857-debian-10-4-buster-linuxcnc-quick-and-easy-install) instructions, linuxcnc fails to start:

LINUXCNC - 2.9.0~pre0
Machine configuration directory is '/home/owhite/linuxcnc/configs/sim.axis'
Machine configuration file is 'axis.ini'
Traceback (most recent call last):
  File "/usr/bin/update_ini", line 11, in <module>
    from tkinter import *
ImportError: No module named tkinter
update script failed in an unexpected way.

This seems to be related to commit 95dc9f07a275 "update_ini.py: python3 compatibility".

There are at least a couple of threads on this issue in the forum:
* [new install, now cant import tkinter](https://forum.linuxcnc.org/9-installing-linuxcnc/38996-new-install-now-cant-import-tkinter)
* [Upgraded to 2.9...LCNC fails on startup - no module named tkinter](https://forum.linuxcnc.org/9-installing-linuxcnc/38985-upgraded-to-2-9-lcnc-fails-on-startup-no-module-named-tkinter)

**Comment by rene-dev** [comment]
fixed by https://github.com/LinuxCNC/linuxcnc/commit/a14b08a706b948b41c1d3ec566fb0b8f42e43421
