### ISSUE TITLE
Wrong preview of rounded rectangle path in probe-basic.

### ISSUE THREAD

**Issue by rmu75** [LinuxCNC/linuxcnc#892]
## Here are the steps I follow to reproduce the issue:

* load g-code file
 
## This is what I expected to happen:

display preview

## This is what happened instead:

displayed preview is wrong (see screenshots). actual motion of the machine is ok.

## It worked properly before this:

2.9 from beginning of june (not sure about exact version, to be determined).

## Information about my hardware and software:

 * I am using this Linux distribution and version (often, shown by `lsb_release -a`): Ubuntu 18.04
 * I am using this kernel version (shown by `uname -a`): 4.19.0-5-rt-amd64 #1 SMP PREEMPT RT Debian 4.19.37-3 (2019-05-15) x86_64 x86_64 x86_64 GNU/Linux
 * I am running ...
   * [ ] A binary version from linuxcnc.org (including buildbot.linuxcnc.org)
   * [x] A binary I built myself
   * [ ] A binary version from some other source besides linuxcnc.org
 * I am using this LinuxCNC version (shown in package manager or, for git versions, `scripts/get-version-from-git`): v2.9.0-pre0-2235-g8e7842fa9
 * I am using this user interface (GUI) (e.g., AXIS, Touchy, gmoccapy, etc): probe-basis
 * I am using this interface hardware vendor and chipset (e.g., parallel port, ethernet port, FPGA card): mesa 7i93

Of note: this seems to be related to a G92 X-offset that seems to be as large as the radius of the wrong circle segments. G-Code file to reproduce and experiments with axis and gmoccapy are in the works.

![image](https://user-images.githubusercontent.com/9028252/85116944-5d29b980-b21e-11ea-9fb8-0ed2b4647ed3.png)
![image](https://user-images.githubusercontent.com/9028252/85117015-7af71e80-b21e-11ea-96bf-7c35b9265b8b.png)

**Comment by rene-dev** [comment]
can you attach the gcode file?

**Comment by rmu75** [comment]
Excerpted g-code showing this issue

[test-circle.txt](https://github.com/LinuxCNC/linuxcnc/files/4804003/test-circle.txt)

**Comment by jepler** [comment]
Atfter modifying the file so that AXIS is content to open it (getting rid of use of tool table and fixing modal gcodes at the start of the program), the toolpath may differ from what is intended, but AXIS and task both trace out the same toolpath.

[test-circle.ngc.txt](https://github.com/LinuxCNC/linuxcnc/files/4805721/test-circle.ngc.txt)
![Screenshot_2020-06-19_11-28-09](https://user-images.githubusercontent.com/1517291/85156661-ff966c80-b21f-11ea-83fd-b4fcc05a00dc.png)

**Comment by rmu75** [comment]
Just tested this again with latest versions of qtpyvcp and probe_basic. It seems to be some interaction with G92 offset, if those are canceled (with G92.1), preview looks like it should, setting an offset and reloading the file show wrong preview again.

**Comment by rmu75** [comment]
So this is probably not a linuxcnc issue per se, I opened an issue here: https://github.com/kcjengr/qtpyvcp/issues/42

**Comment by jepler** [comment]
Feel free to reopen this issue if further investigation indicates a problem in LinuxCNC
