### ISSUE TITLE
thcud.comp

### ISSUE THREAD

**Issue by daiman444** [LinuxCNC/linuxcnc#911]
greetings!
I am using LinuxCNC 2.7.15.
when the component is operating, the cutter jerks up / down when turning on / off the thc, because
if (! enable) {
         z_pos_out = z_pos_in;
         z_fb_out = z_pos_in;

the amount of jerk is equal to:
// Global Variables
variable float offset;

this problem is persistent for the component.

the problem was solved by adding offset to z_pos_in after shutdown. it looks like this:

if (! enable) {
         z_pos_out = z_pos_in + offset;
         z_fb_out = z_pos_in;
thank you for attention!

**Comment by jethornton** [comment]
I have no way to test this but it looks ok to me.

JT

**Comment by petterreinholdtsen** [comment]
See also #675, another issue related to thcud.

**Comment by andypugh** [comment]
It's been a long wait, but I just made this change. Thanks.
