### ISSUE TITLE
2.8 docs errors/misspell: tweaking-steppers.txt

### ISSUE THREAD

**Issue by jmgardeto** [LinuxCNC/linuxcnc#913]
File: ./docs/src/motion/tweaking-steppers.txt

- line 30 says: "The last number in the column labeled 'ovl max' is the most important."
       proposal: "The last number in the column labeled 'Max Jitter' is the most important."
- line 33 says: "that is 10636 nano-seconds, or 10.6 micro-seconds, which is excellent."
       proposal: " that is 6693 nano-seconds, or 6.69 micro-seconds, which is excellent."
                         # number from figure in  Latency Test chapter
- line 40 says: "FixingDapperSMIIssues in the wiki found at wiki.linuxcnc.org"
       proposal: " http://wiki.linuxcnc.org/cgi-bin/wiki.pl?FixingSMIIssues"
- line 42 says: "So, what do the results mean? If your 'ovl max' number is less than"
       proposal: "So, what do the results mean? If your 'Max Jitter' number is less than"
- line 50 says: "nanoseconds) mean the PC is not a good candidate for EMC, regardless of"
       proposal: "nanoseconds) mean the PC is not a good candidate for LinuxCNC, regardless of"
- line 55 says: "using the onboard video. But a $5 used Matrox video card solved the"
       proposal: "using the onboard video. But a $5 used video card solved the"
- line 56 says: "problem - EMC does not require bleeding edge hardware."
       proposal: "problem - LinuxCNC does not require bleeding edge hardware."
- line 97 says: "BASE_PERIOD is the 'heartbeat' of your EMC computer. Every period, the"
       proposal: "BASE_PERIOD is the 'heartbeat' of your LinuxCNC computer. Every period, the"
- line 156 says: "start at 25 us or more, run EMC, and see how things respond. If all is"
       proposal: "start at 25 us or more, run LinuxCNC, and see how things respond. If all is"

**Comment by andypugh** [comment]
Fixed by 2461f4a2869713e82a35fde3c579549e8e5f6a5b
