### ISSUE TITLE
2.8 docs: small cosmetic change in kinematics.txt

### ISSUE THREAD

**Issue by jmgardeto** [LinuxCNC/linuxcnc#914]
When an image is embedded between text, the alignment is poor. The effect is at least ugly.

File: ./docs/src/motion/kinematics.txt

    lines 181-182 says: "We can easily see that image:images/kinematics-math-01.png[],
                         likewise image:images/kinematics-math-02.png[]"
    proposal:  "We can easily see that:
                image::images/kinematics-math-01.png[align="center"]
                likewise: 
                image::images/kinematics-math-02.png[align="center"]"

**Comment by andypugh** [comment]
Addressed by 09c44d34f
