### ISSUE TITLE
some Icons don't look great with Gtk darkmode themes

### ISSUE THREAD

**Issue by rene-dev** [LinuxCNC/linuxcnc#944]
![Screenshot from 2020-10-01 00-11-43](https://user-images.githubusercontent.com/707259/94745368-e18deb80-037a-11eb-89f3-0230dbb3457c.png)

**Comment by gmoccapy** [comment]
This are black icon on a dark background. This will never look good. In this case the user needs to edit the icon to fit his color needs. I have no clue how to set icons depending on theme colors.

I close this issue
