### ISSUE TITLE
onboard keyboard stays open after gmoccapy is closed.

### ISSUE THREAD

**Issue by rene-dev** [LinuxCNC/linuxcnc#949]
this accumulates many onboard instances in the taskbar.

**Comment by gmoccapy** [comment]
I pushed a fix to rene-dev/limuxcmc

FIXED with gmoccapy 3.3.3.3

**Comment by gmoccapy** [comment]
The onboard closes, but throws an error in terminal, thats why i do reopen this issue

**Comment by gmoccapy** [comment]
Pushed a new fix to rene-dev/limuxcmc

This can be closed now
