### ISSUE TITLE
hiding mouse pointer not implemented in gtk3

### ISSUE THREAD

**Issue by rene-dev** [LinuxCNC/linuxcnc#951]
affects touchy and gmoccapy, the code to hide the cursor is commented out.

**Comment by gmoccapy** [comment]
I have pushed a fix for gmoccapy to rene-dev/limuxcmc

IMHO it can be implemented also in TOUCHY

**Comment by gmoccapy** [comment]
In Touchy it should look like so:
`
        def pointer_hide(self, b):
                if self.radiobutton_mask: return
                self.prefs.putpref('invisible_cursor', 1)
                self.invisible_cursor = 1
                win = self.wTree.get_object("MainWindow").get_window()
                cursor = gdk.Cursor(gdk.CursorType.BLANK_CURSOR)
                win.set_cursor(cursor)

        def pointer_show(self, b):
                if self.radiobutton_mask: return
                self.prefs.putpref('invisible_cursor', 0)
                self.invisible_cursor = 0
                win = self.wTree.get_object("MainWindow").get_window()
                cursor = gdk.Cursor(gdk.CursorType.ARROW)
                win.set_cursor(cursor)
`
Infortunately TOUCHY does not start on my PC, getting a bunch of error messages

**Comment by rene-dev** [comment]
fixed in gmoccapy and touchy
