### ISSUE TITLE
lathe macro screen not working with gtk3

### ISSUE THREAD

**Issue by rene-dev** [LinuxCNC/linuxcnc#959]
the svg background is drawn over the UI elements.
uncomment this line to reproduce.
https://github.com/rene-dev/linuxcnc/blob/limuxcmc/configs/sim/gmoccapy/lathe_configs/lathehandler.py#L57
to start screen without linuxcnc:
`gladevcp -d -c gladevcp -u lathehandler.py lathemacro.ui`

**Comment by rene-dev** [comment]
this was fixed by @andypugh, with a new macro screen.

**Comment by andypugh** [comment]
Versions now stored here: https://github.com/andypugh/LatheMacros/releases
