### ISSUE TITLE
Add support for Mesa hardware (7i95 / 7i97 / 7c80) in LinuxCNC 2.8 

### ISSUE THREAD

**Issue by thomam04** [LinuxCNC/linuxcnc#974]
Certain Mesa hardware still requires LinuxCNC 2.9 (development branch) to function. 

Example of hardware: 7i95 / 7i97 / 7c80 

Could we please add support for commonly available Mesa hardware to the hm2 driver in the stable branch 2.8?

**Comment by andypugh** [comment]
What is missing from 2.8? I would have expected them to be covered by the hm2_eth and hm2_rpspi drivers.

**Comment by thomam04** [comment]
I have tested the 7i95 and it's still not supported in 2.8. 

PCW also mentioned, that the 7i95 / 7i97 and 7C80 still requires 2.9. 

https://forum.linuxcnc.org/27-driver-boards/37894-mesa-7i95?start=120#186919

**Comment by andypugh** [comment]
Looking at it, it seems that they would work, except that the driver thinks that the port width is invalid. 
Do you have a way to build LinuxCNC from source or to run the buildbot packages to test? I don't have any of the hardware in question.

**Comment by thomam04** [comment]
Yes, I am currently running 2.9 from source due other reasons. I would just need some instructions on what to change/add in the current 2.8 branch.

**Comment by pcw-mesa** [comment]
2.8 would need the complete hostmot2 driver set to be updated to  2.9 
to work with the 7C80,7I95,7I97. Its not just the port width, those cards require
support for a new firmware module.

**Comment by andypugh** [comment]
@pcw-mesa Do you think we should? 2.8 mainlined Pi support, so it seems a shame not to support the 7C80. The driver is quite well compartmentalised so it can probably be done with low risk.

**Comment by pcw-mesa** [comment]
Lots of people are using 2.9 and I have not heard of any driver related issues
so I think its safe. The additions should only affect users with new firmware 
so I don't really see any downside to pulling all of the 2.9 hostmot2 changes into 2.8

**Comment by andypugh** [comment]
I have created a test branch, which should end up in the buildbot scratch directory soon. 
http://buildbot.linuxcnc.org/dists/buster/scratch-rtpreempt/binary-amd64/
I have no hardware to test with, so hope that Mesa / EUSurplus / JT can run a few tests. 
https://github.com/LinuxCNC/linuxcnc/pull/978

**Comment by andypugh** [comment]
I put in the missing makefile bits later. I don't know if debs got re-made after that.

**Comment by pcw-mesa** [comment]
I cannot use the debs so built from the origin/andypugh/2.8_hm2_update branch

**Comment by andypugh** [comment]
6b67bdd should have fixed that problem. Can you try again?

**Comment by pcw-mesa** [comment]
That problem was fixed with a new fetch and all the new stuff driver seems to be there
One remaining issue is that the hostmot2 manual page does not seem 
to be up to date (for example, it mentions the rcpwm but there is no pin 
description as there is in the 2.9 manual)

**Comment by andypugh** [comment]
I can fix the docs. Can you confirm that the pull request works with the hardware?

**Comment by pcw-mesa** [comment]
Yes it does work at least with a 7I95 (which probably means all the new stuff is there)

**Comment by andypugh** [comment]
f423c5831dd51f32dab485d9ecc11bf2fa02d31c
