### ISSUE TITLE
little error in gmoccapy signal names in 2.8 documentation

### ISSUE THREAD

**Issue by Hans470** [LinuxCNC/linuxcnc#990]
Only a few little errors in 
http://linuxcnc.org/docs/2.8/html/gui/gmoccapy.html#_velocities_and_overrides

The names of the signals

    gmoccapy.rapid.rapid_override.counts
    gmoccapy.rapid.rapid_override.count-enable 
    gmoccapy.rapid.rapid_override.direct-value 
    gmoccapy.rapid.rapid_override.analog-enable 

should be 

    gmoccapy.rapid.rapid-override.counts
    gmoccapy.rapid.rapid-override.count-enable 
    gmoccapy.rapid.rapid-override.direct-value 
    gmoccapy.rapid.rapid-override.analog-enable

**Comment by andypugh** [comment]
0cd671c7760ee1d30e9a5a074d16478d9ed3f803 should fix it

**Comment by Hans470** [comment]
:+1:
